// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

public interface AdReplyInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.AdReplyInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string advertiserName = 1;</code>
   * @return Whether the advertiserName field is set.
   */
  boolean hasAdvertiserName();
  /**
   * <code>optional string advertiserName = 1;</code>
   * @return The advertiserName.
   */
  java.lang.String getAdvertiserName();
  /**
   * <code>optional string advertiserName = 1;</code>
   * @return The bytes for advertiserName.
   */
  com.google.protobuf.ByteString
      getAdvertiserNameBytes();

  /**
   * <code>optional .binary.AdReplyInfo.AdReplyInfoMediaType mediaType = 2;</code>
   * @return Whether the mediaType field is set.
   */
  boolean hasMediaType();
  /**
   * <code>optional .binary.AdReplyInfo.AdReplyInfoMediaType mediaType = 2;</code>
   * @return The mediaType.
   */
  br.com.zapia.wpp.api.ws.binary.protos.AdReplyInfo.AdReplyInfoMediaType getMediaType();

  /**
   * <code>optional bytes jpegThumbnail = 16;</code>
   * @return Whether the jpegThumbnail field is set.
   */
  boolean hasJpegThumbnail();
  /**
   * <code>optional bytes jpegThumbnail = 16;</code>
   * @return The jpegThumbnail.
   */
  com.google.protobuf.ByteString getJpegThumbnail();

  /**
   * <code>optional string caption = 17;</code>
   * @return Whether the caption field is set.
   */
  boolean hasCaption();
  /**
   * <code>optional string caption = 17;</code>
   * @return The caption.
   */
  java.lang.String getCaption();
  /**
   * <code>optional string caption = 17;</code>
   * @return The bytes for caption.
   */
  com.google.protobuf.ByteString
      getCaptionBytes();
}
