// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

public interface AppStateSyncKeyIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.AppStateSyncKeyId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes keyId = 1;</code>
   * @return Whether the keyId field is set.
   */
  boolean hasKeyId();
  /**
   * <code>optional bytes keyId = 1;</code>
   * @return The keyId.
   */
  com.google.protobuf.ByteString getKeyId();
}
