// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

/**
 * Protobuf type {@code binary.BizIdentityInfo}
 */
public final class BizIdentityInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:binary.BizIdentityInfo)
    BizIdentityInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BizIdentityInfo.newBuilder() to construct.
  private BizIdentityInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BizIdentityInfo() {
    vlevel_ = 0;
    hostStorage_ = 0;
    actualActors_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BizIdentityInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BizIdentityInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue value = br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(1, rawValue);
            } else {
              bitField0_ |= 0x00000001;
              vlevel_ = rawValue;
            }
            break;
          }
          case 18: {
            br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) != 0)) {
              subBuilder = vnameCert_.toBuilder();
            }
            vnameCert_ = input.readMessage(br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(vnameCert_);
              vnameCert_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            signed_ = input.readBool();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            revoked_ = input.readBool();
            break;
          }
          case 40: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoHostStorageType value = br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoHostStorageType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(5, rawValue);
            } else {
              bitField0_ |= 0x00000010;
              hostStorage_ = rawValue;
            }
            break;
          }
          case 48: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoActualActorsType value = br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoActualActorsType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(6, rawValue);
            } else {
              bitField0_ |= 0x00000020;
              actualActors_ = rawValue;
            }
            break;
          }
          case 56: {
            bitField0_ |= 0x00000040;
            privacyModeTs_ = input.readUInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_BizIdentityInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_BizIdentityInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.class, br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.Builder.class);
  }

  /**
   * Protobuf enum {@code binary.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue}
   */
  public enum BizIdentityInfoVerifiedLevelValue
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>LOW = 1;</code>
     */
    LOW(1),
    /**
     * <code>HIGH = 2;</code>
     */
    HIGH(2),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>LOW = 1;</code>
     */
    public static final int LOW_VALUE = 1;
    /**
     * <code>HIGH = 2;</code>
     */
    public static final int HIGH_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BizIdentityInfoVerifiedLevelValue valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static BizIdentityInfoVerifiedLevelValue forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return LOW;
        case 2: return HIGH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BizIdentityInfoVerifiedLevelValue>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BizIdentityInfoVerifiedLevelValue> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BizIdentityInfoVerifiedLevelValue>() {
            public BizIdentityInfoVerifiedLevelValue findValueByNumber(int number) {
              return BizIdentityInfoVerifiedLevelValue.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.getDescriptor().getEnumTypes().get(0);
    }

    private static final BizIdentityInfoVerifiedLevelValue[] VALUES = values();

    public static BizIdentityInfoVerifiedLevelValue valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BizIdentityInfoVerifiedLevelValue(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:binary.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue)
  }

  /**
   * Protobuf enum {@code binary.BizIdentityInfo.BizIdentityInfoHostStorageType}
   */
  public enum BizIdentityInfoHostStorageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ON_PREMISE = 0;</code>
     */
    ON_PREMISE(0),
    /**
     * <code>FACEBOOK = 1;</code>
     */
    FACEBOOK(1),
    ;

    /**
     * <code>ON_PREMISE = 0;</code>
     */
    public static final int ON_PREMISE_VALUE = 0;
    /**
     * <code>FACEBOOK = 1;</code>
     */
    public static final int FACEBOOK_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BizIdentityInfoHostStorageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static BizIdentityInfoHostStorageType forNumber(int value) {
      switch (value) {
        case 0: return ON_PREMISE;
        case 1: return FACEBOOK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BizIdentityInfoHostStorageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BizIdentityInfoHostStorageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BizIdentityInfoHostStorageType>() {
            public BizIdentityInfoHostStorageType findValueByNumber(int number) {
              return BizIdentityInfoHostStorageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.getDescriptor().getEnumTypes().get(1);
    }

    private static final BizIdentityInfoHostStorageType[] VALUES = values();

    public static BizIdentityInfoHostStorageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BizIdentityInfoHostStorageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:binary.BizIdentityInfo.BizIdentityInfoHostStorageType)
  }

  /**
   * Protobuf enum {@code binary.BizIdentityInfo.BizIdentityInfoActualActorsType}
   */
  public enum BizIdentityInfoActualActorsType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SELF = 0;</code>
     */
    SELF(0),
    /**
     * <code>BSP = 1;</code>
     */
    BSP(1),
    ;

    /**
     * <code>SELF = 0;</code>
     */
    public static final int SELF_VALUE = 0;
    /**
     * <code>BSP = 1;</code>
     */
    public static final int BSP_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BizIdentityInfoActualActorsType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static BizIdentityInfoActualActorsType forNumber(int value) {
      switch (value) {
        case 0: return SELF;
        case 1: return BSP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BizIdentityInfoActualActorsType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BizIdentityInfoActualActorsType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BizIdentityInfoActualActorsType>() {
            public BizIdentityInfoActualActorsType findValueByNumber(int number) {
              return BizIdentityInfoActualActorsType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.getDescriptor().getEnumTypes().get(2);
    }

    private static final BizIdentityInfoActualActorsType[] VALUES = values();

    public static BizIdentityInfoActualActorsType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BizIdentityInfoActualActorsType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:binary.BizIdentityInfo.BizIdentityInfoActualActorsType)
  }

  private int bitField0_;
  public static final int VLEVEL_FIELD_NUMBER = 1;
  private int vlevel_;
  /**
   * <code>optional .binary.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue vlevel = 1;</code>
   * @return Whether the vlevel field is set.
   */
  @java.lang.Override public boolean hasVlevel() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .binary.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue vlevel = 1;</code>
   * @return The vlevel.
   */
  @java.lang.Override public br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue getVlevel() {
    @SuppressWarnings("deprecation")
    br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue result = br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue.valueOf(vlevel_);
    return result == null ? br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue.UNKNOWN : result;
  }

  public static final int VNAMECERT_FIELD_NUMBER = 2;
  private br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate vnameCert_;
  /**
   * <code>optional .binary.VerifiedNameCertificate vnameCert = 2;</code>
   * @return Whether the vnameCert field is set.
   */
  @java.lang.Override
  public boolean hasVnameCert() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .binary.VerifiedNameCertificate vnameCert = 2;</code>
   * @return The vnameCert.
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate getVnameCert() {
    return vnameCert_ == null ? br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate.getDefaultInstance() : vnameCert_;
  }
  /**
   * <code>optional .binary.VerifiedNameCertificate vnameCert = 2;</code>
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificateOrBuilder getVnameCertOrBuilder() {
    return vnameCert_ == null ? br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate.getDefaultInstance() : vnameCert_;
  }

  public static final int SIGNED_FIELD_NUMBER = 3;
  private boolean signed_;
  /**
   * <code>optional bool signed = 3;</code>
   * @return Whether the signed field is set.
   */
  @java.lang.Override
  public boolean hasSigned() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional bool signed = 3;</code>
   * @return The signed.
   */
  @java.lang.Override
  public boolean getSigned() {
    return signed_;
  }

  public static final int REVOKED_FIELD_NUMBER = 4;
  private boolean revoked_;
  /**
   * <code>optional bool revoked = 4;</code>
   * @return Whether the revoked field is set.
   */
  @java.lang.Override
  public boolean hasRevoked() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional bool revoked = 4;</code>
   * @return The revoked.
   */
  @java.lang.Override
  public boolean getRevoked() {
    return revoked_;
  }

  public static final int HOSTSTORAGE_FIELD_NUMBER = 5;
  private int hostStorage_;
  /**
   * <code>optional .binary.BizIdentityInfo.BizIdentityInfoHostStorageType hostStorage = 5;</code>
   * @return Whether the hostStorage field is set.
   */
  @java.lang.Override public boolean hasHostStorage() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .binary.BizIdentityInfo.BizIdentityInfoHostStorageType hostStorage = 5;</code>
   * @return The hostStorage.
   */
  @java.lang.Override public br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoHostStorageType getHostStorage() {
    @SuppressWarnings("deprecation")
    br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoHostStorageType result = br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoHostStorageType.valueOf(hostStorage_);
    return result == null ? br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoHostStorageType.ON_PREMISE : result;
  }

  public static final int ACTUALACTORS_FIELD_NUMBER = 6;
  private int actualActors_;
  /**
   * <code>optional .binary.BizIdentityInfo.BizIdentityInfoActualActorsType actualActors = 6;</code>
   * @return Whether the actualActors field is set.
   */
  @java.lang.Override public boolean hasActualActors() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional .binary.BizIdentityInfo.BizIdentityInfoActualActorsType actualActors = 6;</code>
   * @return The actualActors.
   */
  @java.lang.Override public br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoActualActorsType getActualActors() {
    @SuppressWarnings("deprecation")
    br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoActualActorsType result = br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoActualActorsType.valueOf(actualActors_);
    return result == null ? br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoActualActorsType.SELF : result;
  }

  public static final int PRIVACYMODETS_FIELD_NUMBER = 7;
  private long privacyModeTs_;
  /**
   * <code>optional uint64 privacyModeTs = 7;</code>
   * @return Whether the privacyModeTs field is set.
   */
  @java.lang.Override
  public boolean hasPrivacyModeTs() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional uint64 privacyModeTs = 7;</code>
   * @return The privacyModeTs.
   */
  @java.lang.Override
  public long getPrivacyModeTs() {
    return privacyModeTs_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, vlevel_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getVnameCert());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBool(3, signed_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeBool(4, revoked_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeEnum(5, hostStorage_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeEnum(6, actualActors_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeUInt64(7, privacyModeTs_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, vlevel_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getVnameCert());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, signed_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, revoked_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, hostStorage_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, actualActors_);
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, privacyModeTs_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo)) {
      return super.equals(obj);
    }
    br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo other = (br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo) obj;

    if (hasVlevel() != other.hasVlevel()) return false;
    if (hasVlevel()) {
      if (vlevel_ != other.vlevel_) return false;
    }
    if (hasVnameCert() != other.hasVnameCert()) return false;
    if (hasVnameCert()) {
      if (!getVnameCert()
          .equals(other.getVnameCert())) return false;
    }
    if (hasSigned() != other.hasSigned()) return false;
    if (hasSigned()) {
      if (getSigned()
          != other.getSigned()) return false;
    }
    if (hasRevoked() != other.hasRevoked()) return false;
    if (hasRevoked()) {
      if (getRevoked()
          != other.getRevoked()) return false;
    }
    if (hasHostStorage() != other.hasHostStorage()) return false;
    if (hasHostStorage()) {
      if (hostStorage_ != other.hostStorage_) return false;
    }
    if (hasActualActors() != other.hasActualActors()) return false;
    if (hasActualActors()) {
      if (actualActors_ != other.actualActors_) return false;
    }
    if (hasPrivacyModeTs() != other.hasPrivacyModeTs()) return false;
    if (hasPrivacyModeTs()) {
      if (getPrivacyModeTs()
          != other.getPrivacyModeTs()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVlevel()) {
      hash = (37 * hash) + VLEVEL_FIELD_NUMBER;
      hash = (53 * hash) + vlevel_;
    }
    if (hasVnameCert()) {
      hash = (37 * hash) + VNAMECERT_FIELD_NUMBER;
      hash = (53 * hash) + getVnameCert().hashCode();
    }
    if (hasSigned()) {
      hash = (37 * hash) + SIGNED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSigned());
    }
    if (hasRevoked()) {
      hash = (37 * hash) + REVOKED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRevoked());
    }
    if (hasHostStorage()) {
      hash = (37 * hash) + HOSTSTORAGE_FIELD_NUMBER;
      hash = (53 * hash) + hostStorage_;
    }
    if (hasActualActors()) {
      hash = (37 * hash) + ACTUALACTORS_FIELD_NUMBER;
      hash = (53 * hash) + actualActors_;
    }
    if (hasPrivacyModeTs()) {
      hash = (37 * hash) + PRIVACYMODETS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPrivacyModeTs());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code binary.BizIdentityInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:binary.BizIdentityInfo)
      br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_BizIdentityInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_BizIdentityInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.class, br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.Builder.class);
    }

    // Construct using br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVnameCertFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      vlevel_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (vnameCertBuilder_ == null) {
        vnameCert_ = null;
      } else {
        vnameCertBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      signed_ = false;
      bitField0_ = (bitField0_ & ~0x00000004);
      revoked_ = false;
      bitField0_ = (bitField0_ & ~0x00000008);
      hostStorage_ = 0;
      bitField0_ = (bitField0_ & ~0x00000010);
      actualActors_ = 0;
      bitField0_ = (bitField0_ & ~0x00000020);
      privacyModeTs_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_BizIdentityInfo_descriptor;
    }

    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo getDefaultInstanceForType() {
      return br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.getDefaultInstance();
    }

    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo build() {
      br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo buildPartial() {
      br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo result = new br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.vlevel_ = vlevel_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (vnameCertBuilder_ == null) {
          result.vnameCert_ = vnameCert_;
        } else {
          result.vnameCert_ = vnameCertBuilder_.build();
        }
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.signed_ = signed_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.revoked_ = revoked_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.hostStorage_ = hostStorage_;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        to_bitField0_ |= 0x00000020;
      }
      result.actualActors_ = actualActors_;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.privacyModeTs_ = privacyModeTs_;
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo) {
        return mergeFrom((br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo other) {
      if (other == br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.getDefaultInstance()) return this;
      if (other.hasVlevel()) {
        setVlevel(other.getVlevel());
      }
      if (other.hasVnameCert()) {
        mergeVnameCert(other.getVnameCert());
      }
      if (other.hasSigned()) {
        setSigned(other.getSigned());
      }
      if (other.hasRevoked()) {
        setRevoked(other.getRevoked());
      }
      if (other.hasHostStorage()) {
        setHostStorage(other.getHostStorage());
      }
      if (other.hasActualActors()) {
        setActualActors(other.getActualActors());
      }
      if (other.hasPrivacyModeTs()) {
        setPrivacyModeTs(other.getPrivacyModeTs());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int vlevel_ = 0;
    /**
     * <code>optional .binary.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue vlevel = 1;</code>
     * @return Whether the vlevel field is set.
     */
    @java.lang.Override public boolean hasVlevel() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .binary.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue vlevel = 1;</code>
     * @return The vlevel.
     */
    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue getVlevel() {
      @SuppressWarnings("deprecation")
      br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue result = br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue.valueOf(vlevel_);
      return result == null ? br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue.UNKNOWN : result;
    }
    /**
     * <code>optional .binary.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue vlevel = 1;</code>
     * @param value The vlevel to set.
     * @return This builder for chaining.
     */
    public Builder setVlevel(br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      vlevel_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .binary.BizIdentityInfo.BizIdentityInfoVerifiedLevelValue vlevel = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearVlevel() {
      bitField0_ = (bitField0_ & ~0x00000001);
      vlevel_ = 0;
      onChanged();
      return this;
    }

    private br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate vnameCert_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate, br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate.Builder, br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificateOrBuilder> vnameCertBuilder_;
    /**
     * <code>optional .binary.VerifiedNameCertificate vnameCert = 2;</code>
     * @return Whether the vnameCert field is set.
     */
    public boolean hasVnameCert() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .binary.VerifiedNameCertificate vnameCert = 2;</code>
     * @return The vnameCert.
     */
    public br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate getVnameCert() {
      if (vnameCertBuilder_ == null) {
        return vnameCert_ == null ? br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate.getDefaultInstance() : vnameCert_;
      } else {
        return vnameCertBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .binary.VerifiedNameCertificate vnameCert = 2;</code>
     */
    public Builder setVnameCert(br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate value) {
      if (vnameCertBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        vnameCert_ = value;
        onChanged();
      } else {
        vnameCertBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .binary.VerifiedNameCertificate vnameCert = 2;</code>
     */
    public Builder setVnameCert(
        br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate.Builder builderForValue) {
      if (vnameCertBuilder_ == null) {
        vnameCert_ = builderForValue.build();
        onChanged();
      } else {
        vnameCertBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .binary.VerifiedNameCertificate vnameCert = 2;</code>
     */
    public Builder mergeVnameCert(br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate value) {
      if (vnameCertBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            vnameCert_ != null &&
            vnameCert_ != br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate.getDefaultInstance()) {
          vnameCert_ =
            br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate.newBuilder(vnameCert_).mergeFrom(value).buildPartial();
        } else {
          vnameCert_ = value;
        }
        onChanged();
      } else {
        vnameCertBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .binary.VerifiedNameCertificate vnameCert = 2;</code>
     */
    public Builder clearVnameCert() {
      if (vnameCertBuilder_ == null) {
        vnameCert_ = null;
        onChanged();
      } else {
        vnameCertBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .binary.VerifiedNameCertificate vnameCert = 2;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate.Builder getVnameCertBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getVnameCertFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .binary.VerifiedNameCertificate vnameCert = 2;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificateOrBuilder getVnameCertOrBuilder() {
      if (vnameCertBuilder_ != null) {
        return vnameCertBuilder_.getMessageOrBuilder();
      } else {
        return vnameCert_ == null ?
            br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate.getDefaultInstance() : vnameCert_;
      }
    }
    /**
     * <code>optional .binary.VerifiedNameCertificate vnameCert = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate, br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate.Builder, br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificateOrBuilder> 
        getVnameCertFieldBuilder() {
      if (vnameCertBuilder_ == null) {
        vnameCertBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate, br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificate.Builder, br.com.zapia.wpp.api.ws.binary.protos.VerifiedNameCertificateOrBuilder>(
                getVnameCert(),
                getParentForChildren(),
                isClean());
        vnameCert_ = null;
      }
      return vnameCertBuilder_;
    }

    private boolean signed_ ;
    /**
     * <code>optional bool signed = 3;</code>
     * @return Whether the signed field is set.
     */
    @java.lang.Override
    public boolean hasSigned() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bool signed = 3;</code>
     * @return The signed.
     */
    @java.lang.Override
    public boolean getSigned() {
      return signed_;
    }
    /**
     * <code>optional bool signed = 3;</code>
     * @param value The signed to set.
     * @return This builder for chaining.
     */
    public Builder setSigned(boolean value) {
      bitField0_ |= 0x00000004;
      signed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool signed = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSigned() {
      bitField0_ = (bitField0_ & ~0x00000004);
      signed_ = false;
      onChanged();
      return this;
    }

    private boolean revoked_ ;
    /**
     * <code>optional bool revoked = 4;</code>
     * @return Whether the revoked field is set.
     */
    @java.lang.Override
    public boolean hasRevoked() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bool revoked = 4;</code>
     * @return The revoked.
     */
    @java.lang.Override
    public boolean getRevoked() {
      return revoked_;
    }
    /**
     * <code>optional bool revoked = 4;</code>
     * @param value The revoked to set.
     * @return This builder for chaining.
     */
    public Builder setRevoked(boolean value) {
      bitField0_ |= 0x00000008;
      revoked_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool revoked = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRevoked() {
      bitField0_ = (bitField0_ & ~0x00000008);
      revoked_ = false;
      onChanged();
      return this;
    }

    private int hostStorage_ = 0;
    /**
     * <code>optional .binary.BizIdentityInfo.BizIdentityInfoHostStorageType hostStorage = 5;</code>
     * @return Whether the hostStorage field is set.
     */
    @java.lang.Override public boolean hasHostStorage() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .binary.BizIdentityInfo.BizIdentityInfoHostStorageType hostStorage = 5;</code>
     * @return The hostStorage.
     */
    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoHostStorageType getHostStorage() {
      @SuppressWarnings("deprecation")
      br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoHostStorageType result = br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoHostStorageType.valueOf(hostStorage_);
      return result == null ? br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoHostStorageType.ON_PREMISE : result;
    }
    /**
     * <code>optional .binary.BizIdentityInfo.BizIdentityInfoHostStorageType hostStorage = 5;</code>
     * @param value The hostStorage to set.
     * @return This builder for chaining.
     */
    public Builder setHostStorage(br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoHostStorageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      hostStorage_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .binary.BizIdentityInfo.BizIdentityInfoHostStorageType hostStorage = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearHostStorage() {
      bitField0_ = (bitField0_ & ~0x00000010);
      hostStorage_ = 0;
      onChanged();
      return this;
    }

    private int actualActors_ = 0;
    /**
     * <code>optional .binary.BizIdentityInfo.BizIdentityInfoActualActorsType actualActors = 6;</code>
     * @return Whether the actualActors field is set.
     */
    @java.lang.Override public boolean hasActualActors() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .binary.BizIdentityInfo.BizIdentityInfoActualActorsType actualActors = 6;</code>
     * @return The actualActors.
     */
    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoActualActorsType getActualActors() {
      @SuppressWarnings("deprecation")
      br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoActualActorsType result = br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoActualActorsType.valueOf(actualActors_);
      return result == null ? br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoActualActorsType.SELF : result;
    }
    /**
     * <code>optional .binary.BizIdentityInfo.BizIdentityInfoActualActorsType actualActors = 6;</code>
     * @param value The actualActors to set.
     * @return This builder for chaining.
     */
    public Builder setActualActors(br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo.BizIdentityInfoActualActorsType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000020;
      actualActors_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .binary.BizIdentityInfo.BizIdentityInfoActualActorsType actualActors = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearActualActors() {
      bitField0_ = (bitField0_ & ~0x00000020);
      actualActors_ = 0;
      onChanged();
      return this;
    }

    private long privacyModeTs_ ;
    /**
     * <code>optional uint64 privacyModeTs = 7;</code>
     * @return Whether the privacyModeTs field is set.
     */
    @java.lang.Override
    public boolean hasPrivacyModeTs() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional uint64 privacyModeTs = 7;</code>
     * @return The privacyModeTs.
     */
    @java.lang.Override
    public long getPrivacyModeTs() {
      return privacyModeTs_;
    }
    /**
     * <code>optional uint64 privacyModeTs = 7;</code>
     * @param value The privacyModeTs to set.
     * @return This builder for chaining.
     */
    public Builder setPrivacyModeTs(long value) {
      bitField0_ |= 0x00000040;
      privacyModeTs_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 privacyModeTs = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrivacyModeTs() {
      bitField0_ = (bitField0_ & ~0x00000040);
      privacyModeTs_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:binary.BizIdentityInfo)
  }

  // @@protoc_insertion_point(class_scope:binary.BizIdentityInfo)
  private static final br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo();
  }

  public static br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<BizIdentityInfo>
      PARSER = new com.google.protobuf.AbstractParser<BizIdentityInfo>() {
    @java.lang.Override
    public BizIdentityInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BizIdentityInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BizIdentityInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BizIdentityInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.BizIdentityInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

