// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

/**
 * Protobuf type {@code binary.Button}
 */
public final class Button extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:binary.Button)
    ButtonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Button.newBuilder() to construct.
  private Button(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Button() {
    buttonId_ = "";
    type_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Button();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Button(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            buttonId_ = bs;
            break;
          }
          case 18: {
            br.com.zapia.wpp.api.ws.binary.protos.ButtonText.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) != 0)) {
              subBuilder = buttonText_.toBuilder();
            }
            buttonText_ = input.readMessage(br.com.zapia.wpp.api.ws.binary.protos.ButtonText.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(buttonText_);
              buttonText_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
            br.com.zapia.wpp.api.ws.binary.protos.Button.ButtonType value = br.com.zapia.wpp.api.ws.binary.protos.Button.ButtonType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(3, rawValue);
            } else {
              bitField0_ |= 0x00000004;
              type_ = rawValue;
            }
            break;
          }
          case 34: {
            br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo.Builder subBuilder = null;
            if (((bitField0_ & 0x00000008) != 0)) {
              subBuilder = nativeFlowInfo_.toBuilder();
            }
            nativeFlowInfo_ = input.readMessage(br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(nativeFlowInfo_);
              nativeFlowInfo_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000008;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_Button_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_Button_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.com.zapia.wpp.api.ws.binary.protos.Button.class, br.com.zapia.wpp.api.ws.binary.protos.Button.Builder.class);
  }

  /**
   * Protobuf enum {@code binary.Button.ButtonType}
   */
  public enum ButtonType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>RESPONSE = 1;</code>
     */
    RESPONSE(1),
    /**
     * <code>NATIVE_FLOW = 2;</code>
     */
    NATIVE_FLOW(2),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>RESPONSE = 1;</code>
     */
    public static final int RESPONSE_VALUE = 1;
    /**
     * <code>NATIVE_FLOW = 2;</code>
     */
    public static final int NATIVE_FLOW_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ButtonType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ButtonType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return RESPONSE;
        case 2: return NATIVE_FLOW;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ButtonType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ButtonType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ButtonType>() {
            public ButtonType findValueByNumber(int number) {
              return ButtonType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return br.com.zapia.wpp.api.ws.binary.protos.Button.getDescriptor().getEnumTypes().get(0);
    }

    private static final ButtonType[] VALUES = values();

    public static ButtonType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ButtonType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:binary.Button.ButtonType)
  }

  private int bitField0_;
  public static final int BUTTONID_FIELD_NUMBER = 1;
  private volatile java.lang.Object buttonId_;
  /**
   * <code>optional string buttonId = 1;</code>
   * @return Whether the buttonId field is set.
   */
  @java.lang.Override
  public boolean hasButtonId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string buttonId = 1;</code>
   * @return The buttonId.
   */
  @java.lang.Override
  public java.lang.String getButtonId() {
    java.lang.Object ref = buttonId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        buttonId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string buttonId = 1;</code>
   * @return The bytes for buttonId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getButtonIdBytes() {
    java.lang.Object ref = buttonId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      buttonId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUTTONTEXT_FIELD_NUMBER = 2;
  private br.com.zapia.wpp.api.ws.binary.protos.ButtonText buttonText_;
  /**
   * <code>optional .binary.ButtonText buttonText = 2;</code>
   * @return Whether the buttonText field is set.
   */
  @java.lang.Override
  public boolean hasButtonText() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .binary.ButtonText buttonText = 2;</code>
   * @return The buttonText.
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.ButtonText getButtonText() {
    return buttonText_ == null ? br.com.zapia.wpp.api.ws.binary.protos.ButtonText.getDefaultInstance() : buttonText_;
  }
  /**
   * <code>optional .binary.ButtonText buttonText = 2;</code>
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.ButtonTextOrBuilder getButtonTextOrBuilder() {
    return buttonText_ == null ? br.com.zapia.wpp.api.ws.binary.protos.ButtonText.getDefaultInstance() : buttonText_;
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private int type_;
  /**
   * <code>optional .binary.Button.ButtonType type = 3;</code>
   * @return Whether the type field is set.
   */
  @java.lang.Override public boolean hasType() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .binary.Button.ButtonType type = 3;</code>
   * @return The type.
   */
  @java.lang.Override public br.com.zapia.wpp.api.ws.binary.protos.Button.ButtonType getType() {
    @SuppressWarnings("deprecation")
    br.com.zapia.wpp.api.ws.binary.protos.Button.ButtonType result = br.com.zapia.wpp.api.ws.binary.protos.Button.ButtonType.valueOf(type_);
    return result == null ? br.com.zapia.wpp.api.ws.binary.protos.Button.ButtonType.UNKNOWN : result;
  }

  public static final int NATIVEFLOWINFO_FIELD_NUMBER = 4;
  private br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo nativeFlowInfo_;
  /**
   * <code>optional .binary.NativeFlowInfo nativeFlowInfo = 4;</code>
   * @return Whether the nativeFlowInfo field is set.
   */
  @java.lang.Override
  public boolean hasNativeFlowInfo() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .binary.NativeFlowInfo nativeFlowInfo = 4;</code>
   * @return The nativeFlowInfo.
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo getNativeFlowInfo() {
    return nativeFlowInfo_ == null ? br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo.getDefaultInstance() : nativeFlowInfo_;
  }
  /**
   * <code>optional .binary.NativeFlowInfo nativeFlowInfo = 4;</code>
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfoOrBuilder getNativeFlowInfoOrBuilder() {
    return nativeFlowInfo_ == null ? br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo.getDefaultInstance() : nativeFlowInfo_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, buttonId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getButtonText());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeEnum(3, type_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getNativeFlowInfo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, buttonId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getButtonText());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, type_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getNativeFlowInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.com.zapia.wpp.api.ws.binary.protos.Button)) {
      return super.equals(obj);
    }
    br.com.zapia.wpp.api.ws.binary.protos.Button other = (br.com.zapia.wpp.api.ws.binary.protos.Button) obj;

    if (hasButtonId() != other.hasButtonId()) return false;
    if (hasButtonId()) {
      if (!getButtonId()
          .equals(other.getButtonId())) return false;
    }
    if (hasButtonText() != other.hasButtonText()) return false;
    if (hasButtonText()) {
      if (!getButtonText()
          .equals(other.getButtonText())) return false;
    }
    if (hasType() != other.hasType()) return false;
    if (hasType()) {
      if (type_ != other.type_) return false;
    }
    if (hasNativeFlowInfo() != other.hasNativeFlowInfo()) return false;
    if (hasNativeFlowInfo()) {
      if (!getNativeFlowInfo()
          .equals(other.getNativeFlowInfo())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasButtonId()) {
      hash = (37 * hash) + BUTTONID_FIELD_NUMBER;
      hash = (53 * hash) + getButtonId().hashCode();
    }
    if (hasButtonText()) {
      hash = (37 * hash) + BUTTONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getButtonText().hashCode();
    }
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
    }
    if (hasNativeFlowInfo()) {
      hash = (37 * hash) + NATIVEFLOWINFO_FIELD_NUMBER;
      hash = (53 * hash) + getNativeFlowInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.com.zapia.wpp.api.ws.binary.protos.Button parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.Button parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.Button parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.Button parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.Button parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.Button parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.Button parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.Button parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.Button parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.Button parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.Button parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.Button parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.com.zapia.wpp.api.ws.binary.protos.Button prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code binary.Button}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:binary.Button)
      br.com.zapia.wpp.api.ws.binary.protos.ButtonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_Button_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_Button_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.zapia.wpp.api.ws.binary.protos.Button.class, br.com.zapia.wpp.api.ws.binary.protos.Button.Builder.class);
    }

    // Construct using br.com.zapia.wpp.api.ws.binary.protos.Button.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getButtonTextFieldBuilder();
        getNativeFlowInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      buttonId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      if (buttonTextBuilder_ == null) {
        buttonText_ = null;
      } else {
        buttonTextBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      type_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (nativeFlowInfoBuilder_ == null) {
        nativeFlowInfo_ = null;
      } else {
        nativeFlowInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_Button_descriptor;
    }

    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.Button getDefaultInstanceForType() {
      return br.com.zapia.wpp.api.ws.binary.protos.Button.getDefaultInstance();
    }

    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.Button build() {
      br.com.zapia.wpp.api.ws.binary.protos.Button result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.Button buildPartial() {
      br.com.zapia.wpp.api.ws.binary.protos.Button result = new br.com.zapia.wpp.api.ws.binary.protos.Button(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.buttonId_ = buttonId_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (buttonTextBuilder_ == null) {
          result.buttonText_ = buttonText_;
        } else {
          result.buttonText_ = buttonTextBuilder_.build();
        }
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.type_ = type_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        if (nativeFlowInfoBuilder_ == null) {
          result.nativeFlowInfo_ = nativeFlowInfo_;
        } else {
          result.nativeFlowInfo_ = nativeFlowInfoBuilder_.build();
        }
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.com.zapia.wpp.api.ws.binary.protos.Button) {
        return mergeFrom((br.com.zapia.wpp.api.ws.binary.protos.Button)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.com.zapia.wpp.api.ws.binary.protos.Button other) {
      if (other == br.com.zapia.wpp.api.ws.binary.protos.Button.getDefaultInstance()) return this;
      if (other.hasButtonId()) {
        bitField0_ |= 0x00000001;
        buttonId_ = other.buttonId_;
        onChanged();
      }
      if (other.hasButtonText()) {
        mergeButtonText(other.getButtonText());
      }
      if (other.hasType()) {
        setType(other.getType());
      }
      if (other.hasNativeFlowInfo()) {
        mergeNativeFlowInfo(other.getNativeFlowInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      br.com.zapia.wpp.api.ws.binary.protos.Button parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (br.com.zapia.wpp.api.ws.binary.protos.Button) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object buttonId_ = "";
    /**
     * <code>optional string buttonId = 1;</code>
     * @return Whether the buttonId field is set.
     */
    public boolean hasButtonId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string buttonId = 1;</code>
     * @return The buttonId.
     */
    public java.lang.String getButtonId() {
      java.lang.Object ref = buttonId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          buttonId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string buttonId = 1;</code>
     * @return The bytes for buttonId.
     */
    public com.google.protobuf.ByteString
        getButtonIdBytes() {
      java.lang.Object ref = buttonId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buttonId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string buttonId = 1;</code>
     * @param value The buttonId to set.
     * @return This builder for chaining.
     */
    public Builder setButtonId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      buttonId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string buttonId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearButtonId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      buttonId_ = getDefaultInstance().getButtonId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string buttonId = 1;</code>
     * @param value The bytes for buttonId to set.
     * @return This builder for chaining.
     */
    public Builder setButtonIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      buttonId_ = value;
      onChanged();
      return this;
    }

    private br.com.zapia.wpp.api.ws.binary.protos.ButtonText buttonText_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.ButtonText, br.com.zapia.wpp.api.ws.binary.protos.ButtonText.Builder, br.com.zapia.wpp.api.ws.binary.protos.ButtonTextOrBuilder> buttonTextBuilder_;
    /**
     * <code>optional .binary.ButtonText buttonText = 2;</code>
     * @return Whether the buttonText field is set.
     */
    public boolean hasButtonText() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .binary.ButtonText buttonText = 2;</code>
     * @return The buttonText.
     */
    public br.com.zapia.wpp.api.ws.binary.protos.ButtonText getButtonText() {
      if (buttonTextBuilder_ == null) {
        return buttonText_ == null ? br.com.zapia.wpp.api.ws.binary.protos.ButtonText.getDefaultInstance() : buttonText_;
      } else {
        return buttonTextBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .binary.ButtonText buttonText = 2;</code>
     */
    public Builder setButtonText(br.com.zapia.wpp.api.ws.binary.protos.ButtonText value) {
      if (buttonTextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        buttonText_ = value;
        onChanged();
      } else {
        buttonTextBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .binary.ButtonText buttonText = 2;</code>
     */
    public Builder setButtonText(
        br.com.zapia.wpp.api.ws.binary.protos.ButtonText.Builder builderForValue) {
      if (buttonTextBuilder_ == null) {
        buttonText_ = builderForValue.build();
        onChanged();
      } else {
        buttonTextBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .binary.ButtonText buttonText = 2;</code>
     */
    public Builder mergeButtonText(br.com.zapia.wpp.api.ws.binary.protos.ButtonText value) {
      if (buttonTextBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            buttonText_ != null &&
            buttonText_ != br.com.zapia.wpp.api.ws.binary.protos.ButtonText.getDefaultInstance()) {
          buttonText_ =
            br.com.zapia.wpp.api.ws.binary.protos.ButtonText.newBuilder(buttonText_).mergeFrom(value).buildPartial();
        } else {
          buttonText_ = value;
        }
        onChanged();
      } else {
        buttonTextBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .binary.ButtonText buttonText = 2;</code>
     */
    public Builder clearButtonText() {
      if (buttonTextBuilder_ == null) {
        buttonText_ = null;
        onChanged();
      } else {
        buttonTextBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .binary.ButtonText buttonText = 2;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.ButtonText.Builder getButtonTextBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getButtonTextFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .binary.ButtonText buttonText = 2;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.ButtonTextOrBuilder getButtonTextOrBuilder() {
      if (buttonTextBuilder_ != null) {
        return buttonTextBuilder_.getMessageOrBuilder();
      } else {
        return buttonText_ == null ?
            br.com.zapia.wpp.api.ws.binary.protos.ButtonText.getDefaultInstance() : buttonText_;
      }
    }
    /**
     * <code>optional .binary.ButtonText buttonText = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.ButtonText, br.com.zapia.wpp.api.ws.binary.protos.ButtonText.Builder, br.com.zapia.wpp.api.ws.binary.protos.ButtonTextOrBuilder> 
        getButtonTextFieldBuilder() {
      if (buttonTextBuilder_ == null) {
        buttonTextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.zapia.wpp.api.ws.binary.protos.ButtonText, br.com.zapia.wpp.api.ws.binary.protos.ButtonText.Builder, br.com.zapia.wpp.api.ws.binary.protos.ButtonTextOrBuilder>(
                getButtonText(),
                getParentForChildren(),
                isClean());
        buttonText_ = null;
      }
      return buttonTextBuilder_;
    }

    private int type_ = 0;
    /**
     * <code>optional .binary.Button.ButtonType type = 3;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override public boolean hasType() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .binary.Button.ButtonType type = 3;</code>
     * @return The type.
     */
    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.Button.ButtonType getType() {
      @SuppressWarnings("deprecation")
      br.com.zapia.wpp.api.ws.binary.protos.Button.ButtonType result = br.com.zapia.wpp.api.ws.binary.protos.Button.ButtonType.valueOf(type_);
      return result == null ? br.com.zapia.wpp.api.ws.binary.protos.Button.ButtonType.UNKNOWN : result;
    }
    /**
     * <code>optional .binary.Button.ButtonType type = 3;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(br.com.zapia.wpp.api.ws.binary.protos.Button.ButtonType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .binary.Button.ButtonType type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000004);
      type_ = 0;
      onChanged();
      return this;
    }

    private br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo nativeFlowInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo, br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo.Builder, br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfoOrBuilder> nativeFlowInfoBuilder_;
    /**
     * <code>optional .binary.NativeFlowInfo nativeFlowInfo = 4;</code>
     * @return Whether the nativeFlowInfo field is set.
     */
    public boolean hasNativeFlowInfo() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .binary.NativeFlowInfo nativeFlowInfo = 4;</code>
     * @return The nativeFlowInfo.
     */
    public br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo getNativeFlowInfo() {
      if (nativeFlowInfoBuilder_ == null) {
        return nativeFlowInfo_ == null ? br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo.getDefaultInstance() : nativeFlowInfo_;
      } else {
        return nativeFlowInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .binary.NativeFlowInfo nativeFlowInfo = 4;</code>
     */
    public Builder setNativeFlowInfo(br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo value) {
      if (nativeFlowInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        nativeFlowInfo_ = value;
        onChanged();
      } else {
        nativeFlowInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .binary.NativeFlowInfo nativeFlowInfo = 4;</code>
     */
    public Builder setNativeFlowInfo(
        br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo.Builder builderForValue) {
      if (nativeFlowInfoBuilder_ == null) {
        nativeFlowInfo_ = builderForValue.build();
        onChanged();
      } else {
        nativeFlowInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .binary.NativeFlowInfo nativeFlowInfo = 4;</code>
     */
    public Builder mergeNativeFlowInfo(br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo value) {
      if (nativeFlowInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
            nativeFlowInfo_ != null &&
            nativeFlowInfo_ != br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo.getDefaultInstance()) {
          nativeFlowInfo_ =
            br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo.newBuilder(nativeFlowInfo_).mergeFrom(value).buildPartial();
        } else {
          nativeFlowInfo_ = value;
        }
        onChanged();
      } else {
        nativeFlowInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .binary.NativeFlowInfo nativeFlowInfo = 4;</code>
     */
    public Builder clearNativeFlowInfo() {
      if (nativeFlowInfoBuilder_ == null) {
        nativeFlowInfo_ = null;
        onChanged();
      } else {
        nativeFlowInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }
    /**
     * <code>optional .binary.NativeFlowInfo nativeFlowInfo = 4;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo.Builder getNativeFlowInfoBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getNativeFlowInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .binary.NativeFlowInfo nativeFlowInfo = 4;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfoOrBuilder getNativeFlowInfoOrBuilder() {
      if (nativeFlowInfoBuilder_ != null) {
        return nativeFlowInfoBuilder_.getMessageOrBuilder();
      } else {
        return nativeFlowInfo_ == null ?
            br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo.getDefaultInstance() : nativeFlowInfo_;
      }
    }
    /**
     * <code>optional .binary.NativeFlowInfo nativeFlowInfo = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo, br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo.Builder, br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfoOrBuilder> 
        getNativeFlowInfoFieldBuilder() {
      if (nativeFlowInfoBuilder_ == null) {
        nativeFlowInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo, br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfo.Builder, br.com.zapia.wpp.api.ws.binary.protos.NativeFlowInfoOrBuilder>(
                getNativeFlowInfo(),
                getParentForChildren(),
                isClean());
        nativeFlowInfo_ = null;
      }
      return nativeFlowInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:binary.Button)
  }

  // @@protoc_insertion_point(class_scope:binary.Button)
  private static final br.com.zapia.wpp.api.ws.binary.protos.Button DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.com.zapia.wpp.api.ws.binary.protos.Button();
  }

  public static br.com.zapia.wpp.api.ws.binary.protos.Button getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Button>
      PARSER = new com.google.protobuf.AbstractParser<Button>() {
    @java.lang.Override
    public Button parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Button(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Button> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Button> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.Button getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

