// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

public interface ContextInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.ContextInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string stanzaId = 1;</code>
   * @return Whether the stanzaId field is set.
   */
  boolean hasStanzaId();
  /**
   * <code>optional string stanzaId = 1;</code>
   * @return The stanzaId.
   */
  java.lang.String getStanzaId();
  /**
   * <code>optional string stanzaId = 1;</code>
   * @return The bytes for stanzaId.
   */
  com.google.protobuf.ByteString
      getStanzaIdBytes();

  /**
   * <code>optional string participant = 2;</code>
   * @return Whether the participant field is set.
   */
  boolean hasParticipant();
  /**
   * <code>optional string participant = 2;</code>
   * @return The participant.
   */
  java.lang.String getParticipant();
  /**
   * <code>optional string participant = 2;</code>
   * @return The bytes for participant.
   */
  com.google.protobuf.ByteString
      getParticipantBytes();

  /**
   * <code>optional .binary.Message quotedMessage = 3;</code>
   * @return Whether the quotedMessage field is set.
   */
  boolean hasQuotedMessage();
  /**
   * <code>optional .binary.Message quotedMessage = 3;</code>
   * @return The quotedMessage.
   */
  br.com.zapia.wpp.api.ws.binary.protos.Message getQuotedMessage();
  /**
   * <code>optional .binary.Message quotedMessage = 3;</code>
   */
  br.com.zapia.wpp.api.ws.binary.protos.MessageOrBuilder getQuotedMessageOrBuilder();

  /**
   * <code>optional string remoteJid = 4;</code>
   * @return Whether the remoteJid field is set.
   */
  boolean hasRemoteJid();
  /**
   * <code>optional string remoteJid = 4;</code>
   * @return The remoteJid.
   */
  java.lang.String getRemoteJid();
  /**
   * <code>optional string remoteJid = 4;</code>
   * @return The bytes for remoteJid.
   */
  com.google.protobuf.ByteString
      getRemoteJidBytes();

  /**
   * <code>repeated string mentionedJid = 15;</code>
   * @return A list containing the mentionedJid.
   */
  java.util.List<java.lang.String>
      getMentionedJidList();
  /**
   * <code>repeated string mentionedJid = 15;</code>
   * @return The count of mentionedJid.
   */
  int getMentionedJidCount();
  /**
   * <code>repeated string mentionedJid = 15;</code>
   * @param index The index of the element to return.
   * @return The mentionedJid at the given index.
   */
  java.lang.String getMentionedJid(int index);
  /**
   * <code>repeated string mentionedJid = 15;</code>
   * @param index The index of the value to return.
   * @return The bytes of the mentionedJid at the given index.
   */
  com.google.protobuf.ByteString
      getMentionedJidBytes(int index);

  /**
   * <code>optional string conversionSource = 18;</code>
   * @return Whether the conversionSource field is set.
   */
  boolean hasConversionSource();
  /**
   * <code>optional string conversionSource = 18;</code>
   * @return The conversionSource.
   */
  java.lang.String getConversionSource();
  /**
   * <code>optional string conversionSource = 18;</code>
   * @return The bytes for conversionSource.
   */
  com.google.protobuf.ByteString
      getConversionSourceBytes();

  /**
   * <code>optional bytes conversionData = 19;</code>
   * @return Whether the conversionData field is set.
   */
  boolean hasConversionData();
  /**
   * <code>optional bytes conversionData = 19;</code>
   * @return The conversionData.
   */
  com.google.protobuf.ByteString getConversionData();

  /**
   * <code>optional uint32 conversionDelaySeconds = 20;</code>
   * @return Whether the conversionDelaySeconds field is set.
   */
  boolean hasConversionDelaySeconds();
  /**
   * <code>optional uint32 conversionDelaySeconds = 20;</code>
   * @return The conversionDelaySeconds.
   */
  int getConversionDelaySeconds();

  /**
   * <code>optional uint32 forwardingScore = 21;</code>
   * @return Whether the forwardingScore field is set.
   */
  boolean hasForwardingScore();
  /**
   * <code>optional uint32 forwardingScore = 21;</code>
   * @return The forwardingScore.
   */
  int getForwardingScore();

  /**
   * <code>optional bool isForwarded = 22;</code>
   * @return Whether the isForwarded field is set.
   */
  boolean hasIsForwarded();
  /**
   * <code>optional bool isForwarded = 22;</code>
   * @return The isForwarded.
   */
  boolean getIsForwarded();

  /**
   * <code>optional .binary.AdReplyInfo quotedAd = 23;</code>
   * @return Whether the quotedAd field is set.
   */
  boolean hasQuotedAd();
  /**
   * <code>optional .binary.AdReplyInfo quotedAd = 23;</code>
   * @return The quotedAd.
   */
  br.com.zapia.wpp.api.ws.binary.protos.AdReplyInfo getQuotedAd();
  /**
   * <code>optional .binary.AdReplyInfo quotedAd = 23;</code>
   */
  br.com.zapia.wpp.api.ws.binary.protos.AdReplyInfoOrBuilder getQuotedAdOrBuilder();

  /**
   * <code>optional .binary.MessageKey placeholderKey = 24;</code>
   * @return Whether the placeholderKey field is set.
   */
  boolean hasPlaceholderKey();
  /**
   * <code>optional .binary.MessageKey placeholderKey = 24;</code>
   * @return The placeholderKey.
   */
  br.com.zapia.wpp.api.ws.binary.protos.MessageKey getPlaceholderKey();
  /**
   * <code>optional .binary.MessageKey placeholderKey = 24;</code>
   */
  br.com.zapia.wpp.api.ws.binary.protos.MessageKeyOrBuilder getPlaceholderKeyOrBuilder();

  /**
   * <code>optional uint32 expiration = 25;</code>
   * @return Whether the expiration field is set.
   */
  boolean hasExpiration();
  /**
   * <code>optional uint32 expiration = 25;</code>
   * @return The expiration.
   */
  int getExpiration();

  /**
   * <code>optional int64 ephemeralSettingTimestamp = 26;</code>
   * @return Whether the ephemeralSettingTimestamp field is set.
   */
  boolean hasEphemeralSettingTimestamp();
  /**
   * <code>optional int64 ephemeralSettingTimestamp = 26;</code>
   * @return The ephemeralSettingTimestamp.
   */
  long getEphemeralSettingTimestamp();

  /**
   * <code>optional bytes ephemeralSharedSecret = 27;</code>
   * @return Whether the ephemeralSharedSecret field is set.
   */
  boolean hasEphemeralSharedSecret();
  /**
   * <code>optional bytes ephemeralSharedSecret = 27;</code>
   * @return The ephemeralSharedSecret.
   */
  com.google.protobuf.ByteString getEphemeralSharedSecret();

  /**
   * <code>optional .binary.ExternalAdReplyInfo externalAdReply = 28;</code>
   * @return Whether the externalAdReply field is set.
   */
  boolean hasExternalAdReply();
  /**
   * <code>optional .binary.ExternalAdReplyInfo externalAdReply = 28;</code>
   * @return The externalAdReply.
   */
  br.com.zapia.wpp.api.ws.binary.protos.ExternalAdReplyInfo getExternalAdReply();
  /**
   * <code>optional .binary.ExternalAdReplyInfo externalAdReply = 28;</code>
   */
  br.com.zapia.wpp.api.ws.binary.protos.ExternalAdReplyInfoOrBuilder getExternalAdReplyOrBuilder();

  /**
   * <code>optional string entryPointConversionSource = 29;</code>
   * @return Whether the entryPointConversionSource field is set.
   */
  boolean hasEntryPointConversionSource();
  /**
   * <code>optional string entryPointConversionSource = 29;</code>
   * @return The entryPointConversionSource.
   */
  java.lang.String getEntryPointConversionSource();
  /**
   * <code>optional string entryPointConversionSource = 29;</code>
   * @return The bytes for entryPointConversionSource.
   */
  com.google.protobuf.ByteString
      getEntryPointConversionSourceBytes();

  /**
   * <code>optional string entryPointConversionApp = 30;</code>
   * @return Whether the entryPointConversionApp field is set.
   */
  boolean hasEntryPointConversionApp();
  /**
   * <code>optional string entryPointConversionApp = 30;</code>
   * @return The entryPointConversionApp.
   */
  java.lang.String getEntryPointConversionApp();
  /**
   * <code>optional string entryPointConversionApp = 30;</code>
   * @return The bytes for entryPointConversionApp.
   */
  com.google.protobuf.ByteString
      getEntryPointConversionAppBytes();

  /**
   * <code>optional uint32 entryPointConversionDelaySeconds = 31;</code>
   * @return Whether the entryPointConversionDelaySeconds field is set.
   */
  boolean hasEntryPointConversionDelaySeconds();
  /**
   * <code>optional uint32 entryPointConversionDelaySeconds = 31;</code>
   * @return The entryPointConversionDelaySeconds.
   */
  int getEntryPointConversionDelaySeconds();
}
