// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

public interface ContactMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.ContactMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string displayName = 1;</code>
   * @return Whether the displayName field is set.
   */
  boolean hasDisplayName();
  /**
   * <code>optional string displayName = 1;</code>
   * @return The displayName.
   */
  java.lang.String getDisplayName();
  /**
   * <code>optional string displayName = 1;</code>
   * @return The bytes for displayName.
   */
  com.google.protobuf.ByteString
      getDisplayNameBytes();

  /**
   * <code>optional string vcard = 16;</code>
   * @return Whether the vcard field is set.
   */
  boolean hasVcard();
  /**
   * <code>optional string vcard = 16;</code>
   * @return The vcard.
   */
  java.lang.String getVcard();
  /**
   * <code>optional string vcard = 16;</code>
   * @return The bytes for vcard.
   */
  com.google.protobuf.ByteString
      getVcardBytes();

  /**
   * <code>optional .binary.ContextInfo contextInfo = 17;</code>
   * @return Whether the contextInfo field is set.
   */
  boolean hasContextInfo();
  /**
   * <code>optional .binary.ContextInfo contextInfo = 17;</code>
   * @return The contextInfo.
   */
  br.com.zapia.wpp.api.ws.binary.protos.ContextInfo getContextInfo();
  /**
   * <code>optional .binary.ContextInfo contextInfo = 17;</code>
   */
  br.com.zapia.wpp.api.ws.binary.protos.ContextInfoOrBuilder getContextInfoOrBuilder();
}
