// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

public interface DeclinePaymentRequestMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.DeclinePaymentRequestMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.MessageKey key = 1;</code>
   * @return Whether the key field is set.
   */
  boolean hasKey();
  /**
   * <code>optional .binary.MessageKey key = 1;</code>
   * @return The key.
   */
  br.com.zapia.wpp.api.ws.binary.protos.MessageKey getKey();
  /**
   * <code>optional .binary.MessageKey key = 1;</code>
   */
  br.com.zapia.wpp.api.ws.binary.protos.MessageKeyOrBuilder getKeyOrBuilder();
}
