// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

public interface ExitCodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.ExitCode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 code = 1;</code>
   * @return Whether the code field is set.
   */
  boolean hasCode();
  /**
   * <code>optional uint64 code = 1;</code>
   * @return The code.
   */
  long getCode();

  /**
   * <code>optional string text = 2;</code>
   * @return Whether the text field is set.
   */
  boolean hasText();
  /**
   * <code>optional string text = 2;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>optional string text = 2;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
