// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

public interface HSMDateTimeUnixEpochOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.HSMDateTimeUnixEpoch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 timestamp = 1;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>optional int64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
