// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

public interface HydratedQuickReplyButtonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.HydratedQuickReplyButton)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string displayText = 1;</code>
   * @return Whether the displayText field is set.
   */
  boolean hasDisplayText();
  /**
   * <code>optional string displayText = 1;</code>
   * @return The displayText.
   */
  java.lang.String getDisplayText();
  /**
   * <code>optional string displayText = 1;</code>
   * @return The bytes for displayText.
   */
  com.google.protobuf.ByteString
      getDisplayTextBytes();

  /**
   * <code>optional string id = 2;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional string id = 2;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 2;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
