// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

public interface HydratedCallButtonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.HydratedCallButton)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string displayText = 1;</code>
   * @return Whether the displayText field is set.
   */
  boolean hasDisplayText();
  /**
   * <code>optional string displayText = 1;</code>
   * @return The displayText.
   */
  java.lang.String getDisplayText();
  /**
   * <code>optional string displayText = 1;</code>
   * @return The bytes for displayText.
   */
  com.google.protobuf.ByteString
      getDisplayTextBytes();

  /**
   * <code>optional string phoneNumber = 2;</code>
   * @return Whether the phoneNumber field is set.
   */
  boolean hasPhoneNumber();
  /**
   * <code>optional string phoneNumber = 2;</code>
   * @return The phoneNumber.
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>optional string phoneNumber = 2;</code>
   * @return The bytes for phoneNumber.
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();
}
