// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

public interface ImageMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.ImageMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string url = 1;</code>
   * @return Whether the url field is set.
   */
  boolean hasUrl();
  /**
   * <code>optional string url = 1;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>optional string url = 1;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>optional string mimetype = 2;</code>
   * @return Whether the mimetype field is set.
   */
  boolean hasMimetype();
  /**
   * <code>optional string mimetype = 2;</code>
   * @return The mimetype.
   */
  java.lang.String getMimetype();
  /**
   * <code>optional string mimetype = 2;</code>
   * @return The bytes for mimetype.
   */
  com.google.protobuf.ByteString
      getMimetypeBytes();

  /**
   * <code>optional string caption = 3;</code>
   * @return Whether the caption field is set.
   */
  boolean hasCaption();
  /**
   * <code>optional string caption = 3;</code>
   * @return The caption.
   */
  java.lang.String getCaption();
  /**
   * <code>optional string caption = 3;</code>
   * @return The bytes for caption.
   */
  com.google.protobuf.ByteString
      getCaptionBytes();

  /**
   * <code>optional bytes fileSha256 = 4;</code>
   * @return Whether the fileSha256 field is set.
   */
  boolean hasFileSha256();
  /**
   * <code>optional bytes fileSha256 = 4;</code>
   * @return The fileSha256.
   */
  com.google.protobuf.ByteString getFileSha256();

  /**
   * <code>optional uint64 fileLength = 5;</code>
   * @return Whether the fileLength field is set.
   */
  boolean hasFileLength();
  /**
   * <code>optional uint64 fileLength = 5;</code>
   * @return The fileLength.
   */
  long getFileLength();

  /**
   * <code>optional uint32 height = 6;</code>
   * @return Whether the height field is set.
   */
  boolean hasHeight();
  /**
   * <code>optional uint32 height = 6;</code>
   * @return The height.
   */
  int getHeight();

  /**
   * <code>optional uint32 width = 7;</code>
   * @return Whether the width field is set.
   */
  boolean hasWidth();
  /**
   * <code>optional uint32 width = 7;</code>
   * @return The width.
   */
  int getWidth();

  /**
   * <code>optional bytes mediaKey = 8;</code>
   * @return Whether the mediaKey field is set.
   */
  boolean hasMediaKey();
  /**
   * <code>optional bytes mediaKey = 8;</code>
   * @return The mediaKey.
   */
  com.google.protobuf.ByteString getMediaKey();

  /**
   * <code>optional bytes fileEncSha256 = 9;</code>
   * @return Whether the fileEncSha256 field is set.
   */
  boolean hasFileEncSha256();
  /**
   * <code>optional bytes fileEncSha256 = 9;</code>
   * @return The fileEncSha256.
   */
  com.google.protobuf.ByteString getFileEncSha256();

  /**
   * <code>repeated .binary.InteractiveAnnotation interactiveAnnotations = 10;</code>
   */
  java.util.List<br.com.zapia.wpp.api.ws.binary.protos.InteractiveAnnotation> 
      getInteractiveAnnotationsList();
  /**
   * <code>repeated .binary.InteractiveAnnotation interactiveAnnotations = 10;</code>
   */
  br.com.zapia.wpp.api.ws.binary.protos.InteractiveAnnotation getInteractiveAnnotations(int index);
  /**
   * <code>repeated .binary.InteractiveAnnotation interactiveAnnotations = 10;</code>
   */
  int getInteractiveAnnotationsCount();
  /**
   * <code>repeated .binary.InteractiveAnnotation interactiveAnnotations = 10;</code>
   */
  java.util.List<? extends br.com.zapia.wpp.api.ws.binary.protos.InteractiveAnnotationOrBuilder> 
      getInteractiveAnnotationsOrBuilderList();
  /**
   * <code>repeated .binary.InteractiveAnnotation interactiveAnnotations = 10;</code>
   */
  br.com.zapia.wpp.api.ws.binary.protos.InteractiveAnnotationOrBuilder getInteractiveAnnotationsOrBuilder(
      int index);

  /**
   * <code>optional string directPath = 11;</code>
   * @return Whether the directPath field is set.
   */
  boolean hasDirectPath();
  /**
   * <code>optional string directPath = 11;</code>
   * @return The directPath.
   */
  java.lang.String getDirectPath();
  /**
   * <code>optional string directPath = 11;</code>
   * @return The bytes for directPath.
   */
  com.google.protobuf.ByteString
      getDirectPathBytes();

  /**
   * <code>optional int64 mediaKeyTimestamp = 12;</code>
   * @return Whether the mediaKeyTimestamp field is set.
   */
  boolean hasMediaKeyTimestamp();
  /**
   * <code>optional int64 mediaKeyTimestamp = 12;</code>
   * @return The mediaKeyTimestamp.
   */
  long getMediaKeyTimestamp();

  /**
   * <code>optional bytes jpegThumbnail = 16;</code>
   * @return Whether the jpegThumbnail field is set.
   */
  boolean hasJpegThumbnail();
  /**
   * <code>optional bytes jpegThumbnail = 16;</code>
   * @return The jpegThumbnail.
   */
  com.google.protobuf.ByteString getJpegThumbnail();

  /**
   * <code>optional .binary.ContextInfo contextInfo = 17;</code>
   * @return Whether the contextInfo field is set.
   */
  boolean hasContextInfo();
  /**
   * <code>optional .binary.ContextInfo contextInfo = 17;</code>
   * @return The contextInfo.
   */
  br.com.zapia.wpp.api.ws.binary.protos.ContextInfo getContextInfo();
  /**
   * <code>optional .binary.ContextInfo contextInfo = 17;</code>
   */
  br.com.zapia.wpp.api.ws.binary.protos.ContextInfoOrBuilder getContextInfoOrBuilder();

  /**
   * <code>optional bytes firstScanSidecar = 18;</code>
   * @return Whether the firstScanSidecar field is set.
   */
  boolean hasFirstScanSidecar();
  /**
   * <code>optional bytes firstScanSidecar = 18;</code>
   * @return The firstScanSidecar.
   */
  com.google.protobuf.ByteString getFirstScanSidecar();

  /**
   * <code>optional uint32 firstScanLength = 19;</code>
   * @return Whether the firstScanLength field is set.
   */
  boolean hasFirstScanLength();
  /**
   * <code>optional uint32 firstScanLength = 19;</code>
   * @return The firstScanLength.
   */
  int getFirstScanLength();

  /**
   * <code>optional uint32 experimentGroupId = 20;</code>
   * @return Whether the experimentGroupId field is set.
   */
  boolean hasExperimentGroupId();
  /**
   * <code>optional uint32 experimentGroupId = 20;</code>
   * @return The experimentGroupId.
   */
  int getExperimentGroupId();

  /**
   * <code>optional bytes scansSidecar = 21;</code>
   * @return Whether the scansSidecar field is set.
   */
  boolean hasScansSidecar();
  /**
   * <code>optional bytes scansSidecar = 21;</code>
   * @return The scansSidecar.
   */
  com.google.protobuf.ByteString getScansSidecar();

  /**
   * <code>repeated uint32 scanLengths = 22;</code>
   * @return A list containing the scanLengths.
   */
  java.util.List<java.lang.Integer> getScanLengthsList();
  /**
   * <code>repeated uint32 scanLengths = 22;</code>
   * @return The count of scanLengths.
   */
  int getScanLengthsCount();
  /**
   * <code>repeated uint32 scanLengths = 22;</code>
   * @param index The index of the element to return.
   * @return The scanLengths at the given index.
   */
  int getScanLengths(int index);

  /**
   * <code>optional bytes midQualityFileSha256 = 23;</code>
   * @return Whether the midQualityFileSha256 field is set.
   */
  boolean hasMidQualityFileSha256();
  /**
   * <code>optional bytes midQualityFileSha256 = 23;</code>
   * @return The midQualityFileSha256.
   */
  com.google.protobuf.ByteString getMidQualityFileSha256();

  /**
   * <code>optional bytes midQualityFileEncSha256 = 24;</code>
   * @return Whether the midQualityFileEncSha256 field is set.
   */
  boolean hasMidQualityFileEncSha256();
  /**
   * <code>optional bytes midQualityFileEncSha256 = 24;</code>
   * @return The midQualityFileEncSha256.
   */
  com.google.protobuf.ByteString getMidQualityFileEncSha256();

  /**
   * <code>optional bool viewOnce = 25;</code>
   * @return Whether the viewOnce field is set.
   */
  boolean hasViewOnce();
  /**
   * <code>optional bool viewOnce = 25;</code>
   * @return The viewOnce.
   */
  boolean getViewOnce();

  /**
   * <code>optional string thumbnailDirectPath = 26;</code>
   * @return Whether the thumbnailDirectPath field is set.
   */
  boolean hasThumbnailDirectPath();
  /**
   * <code>optional string thumbnailDirectPath = 26;</code>
   * @return The thumbnailDirectPath.
   */
  java.lang.String getThumbnailDirectPath();
  /**
   * <code>optional string thumbnailDirectPath = 26;</code>
   * @return The bytes for thumbnailDirectPath.
   */
  com.google.protobuf.ByteString
      getThumbnailDirectPathBytes();

  /**
   * <code>optional bytes thumbnailSha256 = 27;</code>
   * @return Whether the thumbnailSha256 field is set.
   */
  boolean hasThumbnailSha256();
  /**
   * <code>optional bytes thumbnailSha256 = 27;</code>
   * @return The thumbnailSha256.
   */
  com.google.protobuf.ByteString getThumbnailSha256();

  /**
   * <code>optional bytes thumbnailEncSha256 = 28;</code>
   * @return Whether the thumbnailEncSha256 field is set.
   */
  boolean hasThumbnailEncSha256();
  /**
   * <code>optional bytes thumbnailEncSha256 = 28;</code>
   * @return The thumbnailEncSha256.
   */
  com.google.protobuf.ByteString getThumbnailEncSha256();
}
