// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

public interface LocalizedNameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.LocalizedName)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string lg = 1;</code>
   * @return Whether the lg field is set.
   */
  boolean hasLg();
  /**
   * <code>optional string lg = 1;</code>
   * @return The lg.
   */
  java.lang.String getLg();
  /**
   * <code>optional string lg = 1;</code>
   * @return The bytes for lg.
   */
  com.google.protobuf.ByteString
      getLgBytes();

  /**
   * <code>optional string lc = 2;</code>
   * @return Whether the lc field is set.
   */
  boolean hasLc();
  /**
   * <code>optional string lc = 2;</code>
   * @return The lc.
   */
  java.lang.String getLc();
  /**
   * <code>optional string lc = 2;</code>
   * @return The bytes for lc.
   */
  com.google.protobuf.ByteString
      getLcBytes();

  /**
   * <code>optional string verifiedName = 3;</code>
   * @return Whether the verifiedName field is set.
   */
  boolean hasVerifiedName();
  /**
   * <code>optional string verifiedName = 3;</code>
   * @return The verifiedName.
   */
  java.lang.String getVerifiedName();
  /**
   * <code>optional string verifiedName = 3;</code>
   * @return The bytes for verifiedName.
   */
  com.google.protobuf.ByteString
      getVerifiedNameBytes();
}
