// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

/**
 * Protobuf type {@code binary.MarkChatAsReadAction}
 */
public final class MarkChatAsReadAction extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:binary.MarkChatAsReadAction)
    MarkChatAsReadActionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MarkChatAsReadAction.newBuilder() to construct.
  private MarkChatAsReadAction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MarkChatAsReadAction() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MarkChatAsReadAction();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MarkChatAsReadAction(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            read_ = input.readBool();
            break;
          }
          case 18: {
            br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange.Builder subBuilder = null;
            if (((bitField0_ & 0x00000002) != 0)) {
              subBuilder = messageRange_.toBuilder();
            }
            messageRange_ = input.readMessage(br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(messageRange_);
              messageRange_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000002;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_MarkChatAsReadAction_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_MarkChatAsReadAction_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction.class, br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction.Builder.class);
  }

  private int bitField0_;
  public static final int READ_FIELD_NUMBER = 1;
  private boolean read_;
  /**
   * <code>optional bool read = 1;</code>
   * @return Whether the read field is set.
   */
  @java.lang.Override
  public boolean hasRead() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional bool read = 1;</code>
   * @return The read.
   */
  @java.lang.Override
  public boolean getRead() {
    return read_;
  }

  public static final int MESSAGERANGE_FIELD_NUMBER = 2;
  private br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange messageRange_;
  /**
   * <code>optional .binary.SyncActionMessageRange messageRange = 2;</code>
   * @return Whether the messageRange field is set.
   */
  @java.lang.Override
  public boolean hasMessageRange() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .binary.SyncActionMessageRange messageRange = 2;</code>
   * @return The messageRange.
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange getMessageRange() {
    return messageRange_ == null ? br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange.getDefaultInstance() : messageRange_;
  }
  /**
   * <code>optional .binary.SyncActionMessageRange messageRange = 2;</code>
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRangeOrBuilder getMessageRangeOrBuilder() {
    return messageRange_ == null ? br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange.getDefaultInstance() : messageRange_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(1, read_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getMessageRange());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, read_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMessageRange());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction)) {
      return super.equals(obj);
    }
    br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction other = (br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction) obj;

    if (hasRead() != other.hasRead()) return false;
    if (hasRead()) {
      if (getRead()
          != other.getRead()) return false;
    }
    if (hasMessageRange() != other.hasMessageRange()) return false;
    if (hasMessageRange()) {
      if (!getMessageRange()
          .equals(other.getMessageRange())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRead()) {
      hash = (37 * hash) + READ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRead());
    }
    if (hasMessageRange()) {
      hash = (37 * hash) + MESSAGERANGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageRange().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code binary.MarkChatAsReadAction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:binary.MarkChatAsReadAction)
      br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadActionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_MarkChatAsReadAction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_MarkChatAsReadAction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction.class, br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction.Builder.class);
    }

    // Construct using br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMessageRangeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      read_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (messageRangeBuilder_ == null) {
        messageRange_ = null;
      } else {
        messageRangeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_MarkChatAsReadAction_descriptor;
    }

    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction getDefaultInstanceForType() {
      return br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction.getDefaultInstance();
    }

    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction build() {
      br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction buildPartial() {
      br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction result = new br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.read_ = read_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (messageRangeBuilder_ == null) {
          result.messageRange_ = messageRange_;
        } else {
          result.messageRange_ = messageRangeBuilder_.build();
        }
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction) {
        return mergeFrom((br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction other) {
      if (other == br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction.getDefaultInstance()) return this;
      if (other.hasRead()) {
        setRead(other.getRead());
      }
      if (other.hasMessageRange()) {
        mergeMessageRange(other.getMessageRange());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean read_ ;
    /**
     * <code>optional bool read = 1;</code>
     * @return Whether the read field is set.
     */
    @java.lang.Override
    public boolean hasRead() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool read = 1;</code>
     * @return The read.
     */
    @java.lang.Override
    public boolean getRead() {
      return read_;
    }
    /**
     * <code>optional bool read = 1;</code>
     * @param value The read to set.
     * @return This builder for chaining.
     */
    public Builder setRead(boolean value) {
      bitField0_ |= 0x00000001;
      read_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool read = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRead() {
      bitField0_ = (bitField0_ & ~0x00000001);
      read_ = false;
      onChanged();
      return this;
    }

    private br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange messageRange_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange, br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange.Builder, br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRangeOrBuilder> messageRangeBuilder_;
    /**
     * <code>optional .binary.SyncActionMessageRange messageRange = 2;</code>
     * @return Whether the messageRange field is set.
     */
    public boolean hasMessageRange() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .binary.SyncActionMessageRange messageRange = 2;</code>
     * @return The messageRange.
     */
    public br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange getMessageRange() {
      if (messageRangeBuilder_ == null) {
        return messageRange_ == null ? br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange.getDefaultInstance() : messageRange_;
      } else {
        return messageRangeBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .binary.SyncActionMessageRange messageRange = 2;</code>
     */
    public Builder setMessageRange(br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange value) {
      if (messageRangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageRange_ = value;
        onChanged();
      } else {
        messageRangeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .binary.SyncActionMessageRange messageRange = 2;</code>
     */
    public Builder setMessageRange(
        br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange.Builder builderForValue) {
      if (messageRangeBuilder_ == null) {
        messageRange_ = builderForValue.build();
        onChanged();
      } else {
        messageRangeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .binary.SyncActionMessageRange messageRange = 2;</code>
     */
    public Builder mergeMessageRange(br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange value) {
      if (messageRangeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            messageRange_ != null &&
            messageRange_ != br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange.getDefaultInstance()) {
          messageRange_ =
            br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange.newBuilder(messageRange_).mergeFrom(value).buildPartial();
        } else {
          messageRange_ = value;
        }
        onChanged();
      } else {
        messageRangeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .binary.SyncActionMessageRange messageRange = 2;</code>
     */
    public Builder clearMessageRange() {
      if (messageRangeBuilder_ == null) {
        messageRange_ = null;
        onChanged();
      } else {
        messageRangeBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .binary.SyncActionMessageRange messageRange = 2;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange.Builder getMessageRangeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getMessageRangeFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .binary.SyncActionMessageRange messageRange = 2;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRangeOrBuilder getMessageRangeOrBuilder() {
      if (messageRangeBuilder_ != null) {
        return messageRangeBuilder_.getMessageOrBuilder();
      } else {
        return messageRange_ == null ?
            br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange.getDefaultInstance() : messageRange_;
      }
    }
    /**
     * <code>optional .binary.SyncActionMessageRange messageRange = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange, br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange.Builder, br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRangeOrBuilder> 
        getMessageRangeFieldBuilder() {
      if (messageRangeBuilder_ == null) {
        messageRangeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange, br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRange.Builder, br.com.zapia.wpp.api.ws.binary.protos.SyncActionMessageRangeOrBuilder>(
                getMessageRange(),
                getParentForChildren(),
                isClean());
        messageRange_ = null;
      }
      return messageRangeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:binary.MarkChatAsReadAction)
  }

  // @@protoc_insertion_point(class_scope:binary.MarkChatAsReadAction)
  private static final br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction();
  }

  public static br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<MarkChatAsReadAction>
      PARSER = new com.google.protobuf.AbstractParser<MarkChatAsReadAction>() {
    @java.lang.Override
    public MarkChatAsReadAction parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MarkChatAsReadAction(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MarkChatAsReadAction> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MarkChatAsReadAction> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.MarkChatAsReadAction getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

