// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 xDeprecated = 1;</code>
   * @return Whether the xDeprecated field is set.
   */
  boolean hasXDeprecated();
  /**
   * <code>optional int32 xDeprecated = 1;</code>
   * @return The xDeprecated.
   */
  int getXDeprecated();

  /**
   * <code>optional int32 yDeprecated = 2;</code>
   * @return Whether the yDeprecated field is set.
   */
  boolean hasYDeprecated();
  /**
   * <code>optional int32 yDeprecated = 2;</code>
   * @return The yDeprecated.
   */
  int getYDeprecated();

  /**
   * <code>optional double x = 3;</code>
   * @return Whether the x field is set.
   */
  boolean hasX();
  /**
   * <code>optional double x = 3;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>optional double y = 4;</code>
   * @return Whether the y field is set.
   */
  boolean hasY();
  /**
   * <code>optional double y = 4;</code>
   * @return The y.
   */
  double getY();
}
