// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

/**
 * Protobuf type {@code binary.ProductMessage}
 */
public final class ProductMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:binary.ProductMessage)
    ProductMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductMessage.newBuilder() to construct.
  private ProductMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductMessage() {
    businessOwnerJid_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProductMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProductMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = product_.toBuilder();
            }
            product_ = input.readMessage(br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(product_);
              product_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            businessOwnerJid_ = bs;
            break;
          }
          case 34: {
            br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) != 0)) {
              subBuilder = catalog_.toBuilder();
            }
            catalog_ = input.readMessage(br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(catalog_);
              catalog_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          case 138: {
            br.com.zapia.wpp.api.ws.binary.protos.ContextInfo.Builder subBuilder = null;
            if (((bitField0_ & 0x00000008) != 0)) {
              subBuilder = contextInfo_.toBuilder();
            }
            contextInfo_ = input.readMessage(br.com.zapia.wpp.api.ws.binary.protos.ContextInfo.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(contextInfo_);
              contextInfo_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000008;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_ProductMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_ProductMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.com.zapia.wpp.api.ws.binary.protos.ProductMessage.class, br.com.zapia.wpp.api.ws.binary.protos.ProductMessage.Builder.class);
  }

  private int bitField0_;
  public static final int PRODUCT_FIELD_NUMBER = 1;
  private br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot product_;
  /**
   * <code>optional .binary.ProductSnapshot product = 1;</code>
   * @return Whether the product field is set.
   */
  @java.lang.Override
  public boolean hasProduct() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .binary.ProductSnapshot product = 1;</code>
   * @return The product.
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot getProduct() {
    return product_ == null ? br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot.getDefaultInstance() : product_;
  }
  /**
   * <code>optional .binary.ProductSnapshot product = 1;</code>
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshotOrBuilder getProductOrBuilder() {
    return product_ == null ? br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot.getDefaultInstance() : product_;
  }

  public static final int BUSINESSOWNERJID_FIELD_NUMBER = 2;
  private volatile java.lang.Object businessOwnerJid_;
  /**
   * <code>optional string businessOwnerJid = 2;</code>
   * @return Whether the businessOwnerJid field is set.
   */
  @java.lang.Override
  public boolean hasBusinessOwnerJid() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string businessOwnerJid = 2;</code>
   * @return The businessOwnerJid.
   */
  @java.lang.Override
  public java.lang.String getBusinessOwnerJid() {
    java.lang.Object ref = businessOwnerJid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        businessOwnerJid_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string businessOwnerJid = 2;</code>
   * @return The bytes for businessOwnerJid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBusinessOwnerJidBytes() {
    java.lang.Object ref = businessOwnerJid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      businessOwnerJid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATALOG_FIELD_NUMBER = 4;
  private br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot catalog_;
  /**
   * <code>optional .binary.CatalogSnapshot catalog = 4;</code>
   * @return Whether the catalog field is set.
   */
  @java.lang.Override
  public boolean hasCatalog() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .binary.CatalogSnapshot catalog = 4;</code>
   * @return The catalog.
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot getCatalog() {
    return catalog_ == null ? br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot.getDefaultInstance() : catalog_;
  }
  /**
   * <code>optional .binary.CatalogSnapshot catalog = 4;</code>
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshotOrBuilder getCatalogOrBuilder() {
    return catalog_ == null ? br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot.getDefaultInstance() : catalog_;
  }

  public static final int CONTEXTINFO_FIELD_NUMBER = 17;
  private br.com.zapia.wpp.api.ws.binary.protos.ContextInfo contextInfo_;
  /**
   * <code>optional .binary.ContextInfo contextInfo = 17;</code>
   * @return Whether the contextInfo field is set.
   */
  @java.lang.Override
  public boolean hasContextInfo() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .binary.ContextInfo contextInfo = 17;</code>
   * @return The contextInfo.
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.ContextInfo getContextInfo() {
    return contextInfo_ == null ? br.com.zapia.wpp.api.ws.binary.protos.ContextInfo.getDefaultInstance() : contextInfo_;
  }
  /**
   * <code>optional .binary.ContextInfo contextInfo = 17;</code>
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.ContextInfoOrBuilder getContextInfoOrBuilder() {
    return contextInfo_ == null ? br.com.zapia.wpp.api.ws.binary.protos.ContextInfo.getDefaultInstance() : contextInfo_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getProduct());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, businessOwnerJid_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getCatalog());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(17, getContextInfo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getProduct());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, businessOwnerJid_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCatalog());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(17, getContextInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.com.zapia.wpp.api.ws.binary.protos.ProductMessage)) {
      return super.equals(obj);
    }
    br.com.zapia.wpp.api.ws.binary.protos.ProductMessage other = (br.com.zapia.wpp.api.ws.binary.protos.ProductMessage) obj;

    if (hasProduct() != other.hasProduct()) return false;
    if (hasProduct()) {
      if (!getProduct()
          .equals(other.getProduct())) return false;
    }
    if (hasBusinessOwnerJid() != other.hasBusinessOwnerJid()) return false;
    if (hasBusinessOwnerJid()) {
      if (!getBusinessOwnerJid()
          .equals(other.getBusinessOwnerJid())) return false;
    }
    if (hasCatalog() != other.hasCatalog()) return false;
    if (hasCatalog()) {
      if (!getCatalog()
          .equals(other.getCatalog())) return false;
    }
    if (hasContextInfo() != other.hasContextInfo()) return false;
    if (hasContextInfo()) {
      if (!getContextInfo()
          .equals(other.getContextInfo())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasProduct()) {
      hash = (37 * hash) + PRODUCT_FIELD_NUMBER;
      hash = (53 * hash) + getProduct().hashCode();
    }
    if (hasBusinessOwnerJid()) {
      hash = (37 * hash) + BUSINESSOWNERJID_FIELD_NUMBER;
      hash = (53 * hash) + getBusinessOwnerJid().hashCode();
    }
    if (hasCatalog()) {
      hash = (37 * hash) + CATALOG_FIELD_NUMBER;
      hash = (53 * hash) + getCatalog().hashCode();
    }
    if (hasContextInfo()) {
      hash = (37 * hash) + CONTEXTINFO_FIELD_NUMBER;
      hash = (53 * hash) + getContextInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.com.zapia.wpp.api.ws.binary.protos.ProductMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.ProductMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.ProductMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.ProductMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.ProductMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.ProductMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.ProductMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.ProductMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.ProductMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.ProductMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.ProductMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.ProductMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.com.zapia.wpp.api.ws.binary.protos.ProductMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code binary.ProductMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:binary.ProductMessage)
      br.com.zapia.wpp.api.ws.binary.protos.ProductMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_ProductMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_ProductMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.zapia.wpp.api.ws.binary.protos.ProductMessage.class, br.com.zapia.wpp.api.ws.binary.protos.ProductMessage.Builder.class);
    }

    // Construct using br.com.zapia.wpp.api.ws.binary.protos.ProductMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getProductFieldBuilder();
        getCatalogFieldBuilder();
        getContextInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (productBuilder_ == null) {
        product_ = null;
      } else {
        productBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      businessOwnerJid_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      if (catalogBuilder_ == null) {
        catalog_ = null;
      } else {
        catalogBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (contextInfoBuilder_ == null) {
        contextInfo_ = null;
      } else {
        contextInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_ProductMessage_descriptor;
    }

    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.ProductMessage getDefaultInstanceForType() {
      return br.com.zapia.wpp.api.ws.binary.protos.ProductMessage.getDefaultInstance();
    }

    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.ProductMessage build() {
      br.com.zapia.wpp.api.ws.binary.protos.ProductMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.ProductMessage buildPartial() {
      br.com.zapia.wpp.api.ws.binary.protos.ProductMessage result = new br.com.zapia.wpp.api.ws.binary.protos.ProductMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (productBuilder_ == null) {
          result.product_ = product_;
        } else {
          result.product_ = productBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.businessOwnerJid_ = businessOwnerJid_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        if (catalogBuilder_ == null) {
          result.catalog_ = catalog_;
        } else {
          result.catalog_ = catalogBuilder_.build();
        }
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        if (contextInfoBuilder_ == null) {
          result.contextInfo_ = contextInfo_;
        } else {
          result.contextInfo_ = contextInfoBuilder_.build();
        }
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.com.zapia.wpp.api.ws.binary.protos.ProductMessage) {
        return mergeFrom((br.com.zapia.wpp.api.ws.binary.protos.ProductMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.com.zapia.wpp.api.ws.binary.protos.ProductMessage other) {
      if (other == br.com.zapia.wpp.api.ws.binary.protos.ProductMessage.getDefaultInstance()) return this;
      if (other.hasProduct()) {
        mergeProduct(other.getProduct());
      }
      if (other.hasBusinessOwnerJid()) {
        bitField0_ |= 0x00000002;
        businessOwnerJid_ = other.businessOwnerJid_;
        onChanged();
      }
      if (other.hasCatalog()) {
        mergeCatalog(other.getCatalog());
      }
      if (other.hasContextInfo()) {
        mergeContextInfo(other.getContextInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      br.com.zapia.wpp.api.ws.binary.protos.ProductMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (br.com.zapia.wpp.api.ws.binary.protos.ProductMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot product_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot, br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot.Builder, br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshotOrBuilder> productBuilder_;
    /**
     * <code>optional .binary.ProductSnapshot product = 1;</code>
     * @return Whether the product field is set.
     */
    public boolean hasProduct() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .binary.ProductSnapshot product = 1;</code>
     * @return The product.
     */
    public br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot getProduct() {
      if (productBuilder_ == null) {
        return product_ == null ? br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot.getDefaultInstance() : product_;
      } else {
        return productBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .binary.ProductSnapshot product = 1;</code>
     */
    public Builder setProduct(br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot value) {
      if (productBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        product_ = value;
        onChanged();
      } else {
        productBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .binary.ProductSnapshot product = 1;</code>
     */
    public Builder setProduct(
        br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot.Builder builderForValue) {
      if (productBuilder_ == null) {
        product_ = builderForValue.build();
        onChanged();
      } else {
        productBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .binary.ProductSnapshot product = 1;</code>
     */
    public Builder mergeProduct(br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot value) {
      if (productBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            product_ != null &&
            product_ != br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot.getDefaultInstance()) {
          product_ =
            br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot.newBuilder(product_).mergeFrom(value).buildPartial();
        } else {
          product_ = value;
        }
        onChanged();
      } else {
        productBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .binary.ProductSnapshot product = 1;</code>
     */
    public Builder clearProduct() {
      if (productBuilder_ == null) {
        product_ = null;
        onChanged();
      } else {
        productBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .binary.ProductSnapshot product = 1;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot.Builder getProductBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getProductFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .binary.ProductSnapshot product = 1;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshotOrBuilder getProductOrBuilder() {
      if (productBuilder_ != null) {
        return productBuilder_.getMessageOrBuilder();
      } else {
        return product_ == null ?
            br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot.getDefaultInstance() : product_;
      }
    }
    /**
     * <code>optional .binary.ProductSnapshot product = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot, br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot.Builder, br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshotOrBuilder> 
        getProductFieldBuilder() {
      if (productBuilder_ == null) {
        productBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot, br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshot.Builder, br.com.zapia.wpp.api.ws.binary.protos.ProductSnapshotOrBuilder>(
                getProduct(),
                getParentForChildren(),
                isClean());
        product_ = null;
      }
      return productBuilder_;
    }

    private java.lang.Object businessOwnerJid_ = "";
    /**
     * <code>optional string businessOwnerJid = 2;</code>
     * @return Whether the businessOwnerJid field is set.
     */
    public boolean hasBusinessOwnerJid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string businessOwnerJid = 2;</code>
     * @return The businessOwnerJid.
     */
    public java.lang.String getBusinessOwnerJid() {
      java.lang.Object ref = businessOwnerJid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          businessOwnerJid_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string businessOwnerJid = 2;</code>
     * @return The bytes for businessOwnerJid.
     */
    public com.google.protobuf.ByteString
        getBusinessOwnerJidBytes() {
      java.lang.Object ref = businessOwnerJid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        businessOwnerJid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string businessOwnerJid = 2;</code>
     * @param value The businessOwnerJid to set.
     * @return This builder for chaining.
     */
    public Builder setBusinessOwnerJid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      businessOwnerJid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string businessOwnerJid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBusinessOwnerJid() {
      bitField0_ = (bitField0_ & ~0x00000002);
      businessOwnerJid_ = getDefaultInstance().getBusinessOwnerJid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string businessOwnerJid = 2;</code>
     * @param value The bytes for businessOwnerJid to set.
     * @return This builder for chaining.
     */
    public Builder setBusinessOwnerJidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      businessOwnerJid_ = value;
      onChanged();
      return this;
    }

    private br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot catalog_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot, br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot.Builder, br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshotOrBuilder> catalogBuilder_;
    /**
     * <code>optional .binary.CatalogSnapshot catalog = 4;</code>
     * @return Whether the catalog field is set.
     */
    public boolean hasCatalog() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .binary.CatalogSnapshot catalog = 4;</code>
     * @return The catalog.
     */
    public br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot getCatalog() {
      if (catalogBuilder_ == null) {
        return catalog_ == null ? br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot.getDefaultInstance() : catalog_;
      } else {
        return catalogBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .binary.CatalogSnapshot catalog = 4;</code>
     */
    public Builder setCatalog(br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot value) {
      if (catalogBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        catalog_ = value;
        onChanged();
      } else {
        catalogBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .binary.CatalogSnapshot catalog = 4;</code>
     */
    public Builder setCatalog(
        br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot.Builder builderForValue) {
      if (catalogBuilder_ == null) {
        catalog_ = builderForValue.build();
        onChanged();
      } else {
        catalogBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .binary.CatalogSnapshot catalog = 4;</code>
     */
    public Builder mergeCatalog(br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot value) {
      if (catalogBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
            catalog_ != null &&
            catalog_ != br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot.getDefaultInstance()) {
          catalog_ =
            br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot.newBuilder(catalog_).mergeFrom(value).buildPartial();
        } else {
          catalog_ = value;
        }
        onChanged();
      } else {
        catalogBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      return this;
    }
    /**
     * <code>optional .binary.CatalogSnapshot catalog = 4;</code>
     */
    public Builder clearCatalog() {
      if (catalogBuilder_ == null) {
        catalog_ = null;
        onChanged();
      } else {
        catalogBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }
    /**
     * <code>optional .binary.CatalogSnapshot catalog = 4;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot.Builder getCatalogBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getCatalogFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .binary.CatalogSnapshot catalog = 4;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshotOrBuilder getCatalogOrBuilder() {
      if (catalogBuilder_ != null) {
        return catalogBuilder_.getMessageOrBuilder();
      } else {
        return catalog_ == null ?
            br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot.getDefaultInstance() : catalog_;
      }
    }
    /**
     * <code>optional .binary.CatalogSnapshot catalog = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot, br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot.Builder, br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshotOrBuilder> 
        getCatalogFieldBuilder() {
      if (catalogBuilder_ == null) {
        catalogBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot, br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshot.Builder, br.com.zapia.wpp.api.ws.binary.protos.CatalogSnapshotOrBuilder>(
                getCatalog(),
                getParentForChildren(),
                isClean());
        catalog_ = null;
      }
      return catalogBuilder_;
    }

    private br.com.zapia.wpp.api.ws.binary.protos.ContextInfo contextInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.ContextInfo, br.com.zapia.wpp.api.ws.binary.protos.ContextInfo.Builder, br.com.zapia.wpp.api.ws.binary.protos.ContextInfoOrBuilder> contextInfoBuilder_;
    /**
     * <code>optional .binary.ContextInfo contextInfo = 17;</code>
     * @return Whether the contextInfo field is set.
     */
    public boolean hasContextInfo() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .binary.ContextInfo contextInfo = 17;</code>
     * @return The contextInfo.
     */
    public br.com.zapia.wpp.api.ws.binary.protos.ContextInfo getContextInfo() {
      if (contextInfoBuilder_ == null) {
        return contextInfo_ == null ? br.com.zapia.wpp.api.ws.binary.protos.ContextInfo.getDefaultInstance() : contextInfo_;
      } else {
        return contextInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .binary.ContextInfo contextInfo = 17;</code>
     */
    public Builder setContextInfo(br.com.zapia.wpp.api.ws.binary.protos.ContextInfo value) {
      if (contextInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        contextInfo_ = value;
        onChanged();
      } else {
        contextInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .binary.ContextInfo contextInfo = 17;</code>
     */
    public Builder setContextInfo(
        br.com.zapia.wpp.api.ws.binary.protos.ContextInfo.Builder builderForValue) {
      if (contextInfoBuilder_ == null) {
        contextInfo_ = builderForValue.build();
        onChanged();
      } else {
        contextInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .binary.ContextInfo contextInfo = 17;</code>
     */
    public Builder mergeContextInfo(br.com.zapia.wpp.api.ws.binary.protos.ContextInfo value) {
      if (contextInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
            contextInfo_ != null &&
            contextInfo_ != br.com.zapia.wpp.api.ws.binary.protos.ContextInfo.getDefaultInstance()) {
          contextInfo_ =
            br.com.zapia.wpp.api.ws.binary.protos.ContextInfo.newBuilder(contextInfo_).mergeFrom(value).buildPartial();
        } else {
          contextInfo_ = value;
        }
        onChanged();
      } else {
        contextInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .binary.ContextInfo contextInfo = 17;</code>
     */
    public Builder clearContextInfo() {
      if (contextInfoBuilder_ == null) {
        contextInfo_ = null;
        onChanged();
      } else {
        contextInfoBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }
    /**
     * <code>optional .binary.ContextInfo contextInfo = 17;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.ContextInfo.Builder getContextInfoBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getContextInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .binary.ContextInfo contextInfo = 17;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.ContextInfoOrBuilder getContextInfoOrBuilder() {
      if (contextInfoBuilder_ != null) {
        return contextInfoBuilder_.getMessageOrBuilder();
      } else {
        return contextInfo_ == null ?
            br.com.zapia.wpp.api.ws.binary.protos.ContextInfo.getDefaultInstance() : contextInfo_;
      }
    }
    /**
     * <code>optional .binary.ContextInfo contextInfo = 17;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.ContextInfo, br.com.zapia.wpp.api.ws.binary.protos.ContextInfo.Builder, br.com.zapia.wpp.api.ws.binary.protos.ContextInfoOrBuilder> 
        getContextInfoFieldBuilder() {
      if (contextInfoBuilder_ == null) {
        contextInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.zapia.wpp.api.ws.binary.protos.ContextInfo, br.com.zapia.wpp.api.ws.binary.protos.ContextInfo.Builder, br.com.zapia.wpp.api.ws.binary.protos.ContextInfoOrBuilder>(
                getContextInfo(),
                getParentForChildren(),
                isClean());
        contextInfo_ = null;
      }
      return contextInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:binary.ProductMessage)
  }

  // @@protoc_insertion_point(class_scope:binary.ProductMessage)
  private static final br.com.zapia.wpp.api.ws.binary.protos.ProductMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.com.zapia.wpp.api.ws.binary.protos.ProductMessage();
  }

  public static br.com.zapia.wpp.api.ws.binary.protos.ProductMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<ProductMessage>
      PARSER = new com.google.protobuf.AbstractParser<ProductMessage>() {
    @java.lang.Override
    public ProductMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProductMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProductMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.ProductMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

