// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

public interface ProductSnapshotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.ProductSnapshot)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.ImageMessage productImage = 1;</code>
   * @return Whether the productImage field is set.
   */
  boolean hasProductImage();
  /**
   * <code>optional .binary.ImageMessage productImage = 1;</code>
   * @return The productImage.
   */
  br.com.zapia.wpp.api.ws.binary.protos.ImageMessage getProductImage();
  /**
   * <code>optional .binary.ImageMessage productImage = 1;</code>
   */
  br.com.zapia.wpp.api.ws.binary.protos.ImageMessageOrBuilder getProductImageOrBuilder();

  /**
   * <code>optional string productId = 2;</code>
   * @return Whether the productId field is set.
   */
  boolean hasProductId();
  /**
   * <code>optional string productId = 2;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <code>optional string productId = 2;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>optional string title = 3;</code>
   * @return Whether the title field is set.
   */
  boolean hasTitle();
  /**
   * <code>optional string title = 3;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>optional string title = 3;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>optional string description = 4;</code>
   * @return Whether the description field is set.
   */
  boolean hasDescription();
  /**
   * <code>optional string description = 4;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>optional string description = 4;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>optional string currencyCode = 5;</code>
   * @return Whether the currencyCode field is set.
   */
  boolean hasCurrencyCode();
  /**
   * <code>optional string currencyCode = 5;</code>
   * @return The currencyCode.
   */
  java.lang.String getCurrencyCode();
  /**
   * <code>optional string currencyCode = 5;</code>
   * @return The bytes for currencyCode.
   */
  com.google.protobuf.ByteString
      getCurrencyCodeBytes();

  /**
   * <code>optional int64 priceAmount1000 = 6;</code>
   * @return Whether the priceAmount1000 field is set.
   */
  boolean hasPriceAmount1000();
  /**
   * <code>optional int64 priceAmount1000 = 6;</code>
   * @return The priceAmount1000.
   */
  long getPriceAmount1000();

  /**
   * <code>optional string retailerId = 7;</code>
   * @return Whether the retailerId field is set.
   */
  boolean hasRetailerId();
  /**
   * <code>optional string retailerId = 7;</code>
   * @return The retailerId.
   */
  java.lang.String getRetailerId();
  /**
   * <code>optional string retailerId = 7;</code>
   * @return The bytes for retailerId.
   */
  com.google.protobuf.ByteString
      getRetailerIdBytes();

  /**
   * <code>optional string url = 8;</code>
   * @return Whether the url field is set.
   */
  boolean hasUrl();
  /**
   * <code>optional string url = 8;</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>optional string url = 8;</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>optional uint32 productImageCount = 9;</code>
   * @return Whether the productImageCount field is set.
   */
  boolean hasProductImageCount();
  /**
   * <code>optional uint32 productImageCount = 9;</code>
   * @return The productImageCount.
   */
  int getProductImageCount();

  /**
   * <code>optional string firstImageId = 11;</code>
   * @return Whether the firstImageId field is set.
   */
  boolean hasFirstImageId();
  /**
   * <code>optional string firstImageId = 11;</code>
   * @return The firstImageId.
   */
  java.lang.String getFirstImageId();
  /**
   * <code>optional string firstImageId = 11;</code>
   * @return The bytes for firstImageId.
   */
  com.google.protobuf.ByteString
      getFirstImageIdBytes();

  /**
   * <code>optional int64 salePriceAmount1000 = 12;</code>
   * @return Whether the salePriceAmount1000 field is set.
   */
  boolean hasSalePriceAmount1000();
  /**
   * <code>optional int64 salePriceAmount1000 = 12;</code>
   * @return The salePriceAmount1000.
   */
  long getSalePriceAmount1000();
}
