// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

public interface ProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.Product)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string productId = 1;</code>
   * @return Whether the productId field is set.
   */
  boolean hasProductId();
  /**
   * <code>optional string productId = 1;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <code>optional string productId = 1;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();
}
