// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

public interface ProtocolMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.ProtocolMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.MessageKey key = 1;</code>
   * @return Whether the key field is set.
   */
  boolean hasKey();
  /**
   * <code>optional .binary.MessageKey key = 1;</code>
   * @return The key.
   */
  br.com.zapia.wpp.api.ws.binary.protos.MessageKey getKey();
  /**
   * <code>optional .binary.MessageKey key = 1;</code>
   */
  br.com.zapia.wpp.api.ws.binary.protos.MessageKeyOrBuilder getKeyOrBuilder();

  /**
   * <code>optional .binary.ProtocolMessage.ProtocolMessageType type = 2;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>optional .binary.ProtocolMessage.ProtocolMessageType type = 2;</code>
   * @return The type.
   */
  br.com.zapia.wpp.api.ws.binary.protos.ProtocolMessage.ProtocolMessageType getType();

  /**
   * <code>optional uint32 ephemeralExpiration = 4;</code>
   * @return Whether the ephemeralExpiration field is set.
   */
  boolean hasEphemeralExpiration();
  /**
   * <code>optional uint32 ephemeralExpiration = 4;</code>
   * @return The ephemeralExpiration.
   */
  int getEphemeralExpiration();

  /**
   * <code>optional int64 ephemeralSettingTimestamp = 5;</code>
   * @return Whether the ephemeralSettingTimestamp field is set.
   */
  boolean hasEphemeralSettingTimestamp();
  /**
   * <code>optional int64 ephemeralSettingTimestamp = 5;</code>
   * @return The ephemeralSettingTimestamp.
   */
  long getEphemeralSettingTimestamp();

  /**
   * <code>optional .binary.HistorySyncNotification historySyncNotification = 6;</code>
   * @return Whether the historySyncNotification field is set.
   */
  boolean hasHistorySyncNotification();
  /**
   * <code>optional .binary.HistorySyncNotification historySyncNotification = 6;</code>
   * @return The historySyncNotification.
   */
  br.com.zapia.wpp.api.ws.binary.protos.HistorySyncNotification getHistorySyncNotification();
  /**
   * <code>optional .binary.HistorySyncNotification historySyncNotification = 6;</code>
   */
  br.com.zapia.wpp.api.ws.binary.protos.HistorySyncNotificationOrBuilder getHistorySyncNotificationOrBuilder();

  /**
   * <code>optional .binary.AppStateSyncKeyShare appStateSyncKeyShare = 7;</code>
   * @return Whether the appStateSyncKeyShare field is set.
   */
  boolean hasAppStateSyncKeyShare();
  /**
   * <code>optional .binary.AppStateSyncKeyShare appStateSyncKeyShare = 7;</code>
   * @return The appStateSyncKeyShare.
   */
  br.com.zapia.wpp.api.ws.binary.protos.AppStateSyncKeyShare getAppStateSyncKeyShare();
  /**
   * <code>optional .binary.AppStateSyncKeyShare appStateSyncKeyShare = 7;</code>
   */
  br.com.zapia.wpp.api.ws.binary.protos.AppStateSyncKeyShareOrBuilder getAppStateSyncKeyShareOrBuilder();

  /**
   * <code>optional .binary.AppStateSyncKeyRequest appStateSyncKeyRequest = 8;</code>
   * @return Whether the appStateSyncKeyRequest field is set.
   */
  boolean hasAppStateSyncKeyRequest();
  /**
   * <code>optional .binary.AppStateSyncKeyRequest appStateSyncKeyRequest = 8;</code>
   * @return The appStateSyncKeyRequest.
   */
  br.com.zapia.wpp.api.ws.binary.protos.AppStateSyncKeyRequest getAppStateSyncKeyRequest();
  /**
   * <code>optional .binary.AppStateSyncKeyRequest appStateSyncKeyRequest = 8;</code>
   */
  br.com.zapia.wpp.api.ws.binary.protos.AppStateSyncKeyRequestOrBuilder getAppStateSyncKeyRequestOrBuilder();

  /**
   * <code>optional .binary.InitialSecurityNotificationSettingSync initialSecurityNotificationSettingSync = 9;</code>
   * @return Whether the initialSecurityNotificationSettingSync field is set.
   */
  boolean hasInitialSecurityNotificationSettingSync();
  /**
   * <code>optional .binary.InitialSecurityNotificationSettingSync initialSecurityNotificationSettingSync = 9;</code>
   * @return The initialSecurityNotificationSettingSync.
   */
  br.com.zapia.wpp.api.ws.binary.protos.InitialSecurityNotificationSettingSync getInitialSecurityNotificationSettingSync();
  /**
   * <code>optional .binary.InitialSecurityNotificationSettingSync initialSecurityNotificationSettingSync = 9;</code>
   */
  br.com.zapia.wpp.api.ws.binary.protos.InitialSecurityNotificationSettingSyncOrBuilder getInitialSecurityNotificationSettingSyncOrBuilder();

  /**
   * <code>optional .binary.AppStateFatalExceptionNotification appStateFatalExceptionNotification = 10;</code>
   * @return Whether the appStateFatalExceptionNotification field is set.
   */
  boolean hasAppStateFatalExceptionNotification();
  /**
   * <code>optional .binary.AppStateFatalExceptionNotification appStateFatalExceptionNotification = 10;</code>
   * @return The appStateFatalExceptionNotification.
   */
  br.com.zapia.wpp.api.ws.binary.protos.AppStateFatalExceptionNotification getAppStateFatalExceptionNotification();
  /**
   * <code>optional .binary.AppStateFatalExceptionNotification appStateFatalExceptionNotification = 10;</code>
   */
  br.com.zapia.wpp.api.ws.binary.protos.AppStateFatalExceptionNotificationOrBuilder getAppStateFatalExceptionNotificationOrBuilder();
}
