// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

/**
 * Protobuf type {@code binary.SyncdSnapshot}
 */
public final class SyncdSnapshot extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:binary.SyncdSnapshot)
    SyncdSnapshotOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SyncdSnapshot.newBuilder() to construct.
  private SyncdSnapshot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SyncdSnapshot() {
    records_ = java.util.Collections.emptyList();
    mac_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SyncdSnapshot();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SyncdSnapshot(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = version_.toBuilder();
            }
            version_ = input.readMessage(br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(version_);
              version_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              records_ = new java.util.ArrayList<br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord>();
              mutable_bitField0_ |= 0x00000002;
            }
            records_.add(
                input.readMessage(br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord.PARSER, extensionRegistry));
            break;
          }
          case 26: {
            bitField0_ |= 0x00000002;
            mac_ = input.readBytes();
            break;
          }
          case 34: {
            br.com.zapia.wpp.api.ws.binary.protos.KeyId.Builder subBuilder = null;
            if (((bitField0_ & 0x00000004) != 0)) {
              subBuilder = keyId_.toBuilder();
            }
            keyId_ = input.readMessage(br.com.zapia.wpp.api.ws.binary.protos.KeyId.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(keyId_);
              keyId_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000004;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        records_ = java.util.Collections.unmodifiableList(records_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_SyncdSnapshot_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_SyncdSnapshot_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot.class, br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot.Builder.class);
  }

  private int bitField0_;
  public static final int VERSION_FIELD_NUMBER = 1;
  private br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion version_;
  /**
   * <code>optional .binary.SyncdVersion version = 1;</code>
   * @return Whether the version field is set.
   */
  @java.lang.Override
  public boolean hasVersion() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .binary.SyncdVersion version = 1;</code>
   * @return The version.
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion getVersion() {
    return version_ == null ? br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion.getDefaultInstance() : version_;
  }
  /**
   * <code>optional .binary.SyncdVersion version = 1;</code>
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.SyncdVersionOrBuilder getVersionOrBuilder() {
    return version_ == null ? br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion.getDefaultInstance() : version_;
  }

  public static final int RECORDS_FIELD_NUMBER = 2;
  private java.util.List<br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord> records_;
  /**
   * <code>repeated .binary.SyncdRecord records = 2;</code>
   */
  @java.lang.Override
  public java.util.List<br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord> getRecordsList() {
    return records_;
  }
  /**
   * <code>repeated .binary.SyncdRecord records = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends br.com.zapia.wpp.api.ws.binary.protos.SyncdRecordOrBuilder> 
      getRecordsOrBuilderList() {
    return records_;
  }
  /**
   * <code>repeated .binary.SyncdRecord records = 2;</code>
   */
  @java.lang.Override
  public int getRecordsCount() {
    return records_.size();
  }
  /**
   * <code>repeated .binary.SyncdRecord records = 2;</code>
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord getRecords(int index) {
    return records_.get(index);
  }
  /**
   * <code>repeated .binary.SyncdRecord records = 2;</code>
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.SyncdRecordOrBuilder getRecordsOrBuilder(
      int index) {
    return records_.get(index);
  }

  public static final int MAC_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString mac_;
  /**
   * <code>optional bytes mac = 3;</code>
   * @return Whether the mac field is set.
   */
  @java.lang.Override
  public boolean hasMac() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional bytes mac = 3;</code>
   * @return The mac.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getMac() {
    return mac_;
  }

  public static final int KEYID_FIELD_NUMBER = 4;
  private br.com.zapia.wpp.api.ws.binary.protos.KeyId keyId_;
  /**
   * <code>optional .binary.KeyId keyId = 4;</code>
   * @return Whether the keyId field is set.
   */
  @java.lang.Override
  public boolean hasKeyId() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .binary.KeyId keyId = 4;</code>
   * @return The keyId.
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.KeyId getKeyId() {
    return keyId_ == null ? br.com.zapia.wpp.api.ws.binary.protos.KeyId.getDefaultInstance() : keyId_;
  }
  /**
   * <code>optional .binary.KeyId keyId = 4;</code>
   */
  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.KeyIdOrBuilder getKeyIdOrBuilder() {
    return keyId_ == null ? br.com.zapia.wpp.api.ws.binary.protos.KeyId.getDefaultInstance() : keyId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getVersion());
    }
    for (int i = 0; i < records_.size(); i++) {
      output.writeMessage(2, records_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBytes(3, mac_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getKeyId());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getVersion());
    }
    for (int i = 0; i < records_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, records_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, mac_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getKeyId());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot)) {
      return super.equals(obj);
    }
    br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot other = (br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot) obj;

    if (hasVersion() != other.hasVersion()) return false;
    if (hasVersion()) {
      if (!getVersion()
          .equals(other.getVersion())) return false;
    }
    if (!getRecordsList()
        .equals(other.getRecordsList())) return false;
    if (hasMac() != other.hasMac()) return false;
    if (hasMac()) {
      if (!getMac()
          .equals(other.getMac())) return false;
    }
    if (hasKeyId() != other.hasKeyId()) return false;
    if (hasKeyId()) {
      if (!getKeyId()
          .equals(other.getKeyId())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVersion()) {
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
    }
    if (getRecordsCount() > 0) {
      hash = (37 * hash) + RECORDS_FIELD_NUMBER;
      hash = (53 * hash) + getRecordsList().hashCode();
    }
    if (hasMac()) {
      hash = (37 * hash) + MAC_FIELD_NUMBER;
      hash = (53 * hash) + getMac().hashCode();
    }
    if (hasKeyId()) {
      hash = (37 * hash) + KEYID_FIELD_NUMBER;
      hash = (53 * hash) + getKeyId().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code binary.SyncdSnapshot}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:binary.SyncdSnapshot)
      br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshotOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_SyncdSnapshot_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_SyncdSnapshot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot.class, br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot.Builder.class);
    }

    // Construct using br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getVersionFieldBuilder();
        getRecordsFieldBuilder();
        getKeyIdFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (versionBuilder_ == null) {
        version_ = null;
      } else {
        versionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (recordsBuilder_ == null) {
        records_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        recordsBuilder_.clear();
      }
      mac_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (keyIdBuilder_ == null) {
        keyId_ = null;
      } else {
        keyIdBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.com.zapia.wpp.api.ws.binary.protos.WaMessageProtos.internal_static_binary_SyncdSnapshot_descriptor;
    }

    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot getDefaultInstanceForType() {
      return br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot.getDefaultInstance();
    }

    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot build() {
      br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot buildPartial() {
      br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot result = new br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (versionBuilder_ == null) {
          result.version_ = version_;
        } else {
          result.version_ = versionBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (recordsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          records_ = java.util.Collections.unmodifiableList(records_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.records_ = records_;
      } else {
        result.records_ = recordsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.mac_ = mac_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        if (keyIdBuilder_ == null) {
          result.keyId_ = keyId_;
        } else {
          result.keyId_ = keyIdBuilder_.build();
        }
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot) {
        return mergeFrom((br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot other) {
      if (other == br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot.getDefaultInstance()) return this;
      if (other.hasVersion()) {
        mergeVersion(other.getVersion());
      }
      if (recordsBuilder_ == null) {
        if (!other.records_.isEmpty()) {
          if (records_.isEmpty()) {
            records_ = other.records_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRecordsIsMutable();
            records_.addAll(other.records_);
          }
          onChanged();
        }
      } else {
        if (!other.records_.isEmpty()) {
          if (recordsBuilder_.isEmpty()) {
            recordsBuilder_.dispose();
            recordsBuilder_ = null;
            records_ = other.records_;
            bitField0_ = (bitField0_ & ~0x00000002);
            recordsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRecordsFieldBuilder() : null;
          } else {
            recordsBuilder_.addAllMessages(other.records_);
          }
        }
      }
      if (other.hasMac()) {
        setMac(other.getMac());
      }
      if (other.hasKeyId()) {
        mergeKeyId(other.getKeyId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion version_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion, br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion.Builder, br.com.zapia.wpp.api.ws.binary.protos.SyncdVersionOrBuilder> versionBuilder_;
    /**
     * <code>optional .binary.SyncdVersion version = 1;</code>
     * @return Whether the version field is set.
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .binary.SyncdVersion version = 1;</code>
     * @return The version.
     */
    public br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion getVersion() {
      if (versionBuilder_ == null) {
        return version_ == null ? br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion.getDefaultInstance() : version_;
      } else {
        return versionBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .binary.SyncdVersion version = 1;</code>
     */
    public Builder setVersion(br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion value) {
      if (versionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        version_ = value;
        onChanged();
      } else {
        versionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .binary.SyncdVersion version = 1;</code>
     */
    public Builder setVersion(
        br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion.Builder builderForValue) {
      if (versionBuilder_ == null) {
        version_ = builderForValue.build();
        onChanged();
      } else {
        versionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .binary.SyncdVersion version = 1;</code>
     */
    public Builder mergeVersion(br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion value) {
      if (versionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            version_ != null &&
            version_ != br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion.getDefaultInstance()) {
          version_ =
            br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion.newBuilder(version_).mergeFrom(value).buildPartial();
        } else {
          version_ = value;
        }
        onChanged();
      } else {
        versionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>optional .binary.SyncdVersion version = 1;</code>
     */
    public Builder clearVersion() {
      if (versionBuilder_ == null) {
        version_ = null;
        onChanged();
      } else {
        versionBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>optional .binary.SyncdVersion version = 1;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion.Builder getVersionBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getVersionFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .binary.SyncdVersion version = 1;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.SyncdVersionOrBuilder getVersionOrBuilder() {
      if (versionBuilder_ != null) {
        return versionBuilder_.getMessageOrBuilder();
      } else {
        return version_ == null ?
            br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion.getDefaultInstance() : version_;
      }
    }
    /**
     * <code>optional .binary.SyncdVersion version = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion, br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion.Builder, br.com.zapia.wpp.api.ws.binary.protos.SyncdVersionOrBuilder> 
        getVersionFieldBuilder() {
      if (versionBuilder_ == null) {
        versionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion, br.com.zapia.wpp.api.ws.binary.protos.SyncdVersion.Builder, br.com.zapia.wpp.api.ws.binary.protos.SyncdVersionOrBuilder>(
                getVersion(),
                getParentForChildren(),
                isClean());
        version_ = null;
      }
      return versionBuilder_;
    }

    private java.util.List<br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord> records_ =
      java.util.Collections.emptyList();
    private void ensureRecordsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        records_ = new java.util.ArrayList<br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord>(records_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord, br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord.Builder, br.com.zapia.wpp.api.ws.binary.protos.SyncdRecordOrBuilder> recordsBuilder_;

    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public java.util.List<br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord> getRecordsList() {
      if (recordsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(records_);
      } else {
        return recordsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public int getRecordsCount() {
      if (recordsBuilder_ == null) {
        return records_.size();
      } else {
        return recordsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord getRecords(int index) {
      if (recordsBuilder_ == null) {
        return records_.get(index);
      } else {
        return recordsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public Builder setRecords(
        int index, br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.set(index, value);
        onChanged();
      } else {
        recordsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public Builder setRecords(
        int index, br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.set(index, builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public Builder addRecords(br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.add(value);
        onChanged();
      } else {
        recordsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public Builder addRecords(
        int index, br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord value) {
      if (recordsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRecordsIsMutable();
        records_.add(index, value);
        onChanged();
      } else {
        recordsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public Builder addRecords(
        br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.add(builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public Builder addRecords(
        int index, br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord.Builder builderForValue) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.add(index, builderForValue.build());
        onChanged();
      } else {
        recordsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public Builder addAllRecords(
        java.lang.Iterable<? extends br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord> values) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, records_);
        onChanged();
      } else {
        recordsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public Builder clearRecords() {
      if (recordsBuilder_ == null) {
        records_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        recordsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public Builder removeRecords(int index) {
      if (recordsBuilder_ == null) {
        ensureRecordsIsMutable();
        records_.remove(index);
        onChanged();
      } else {
        recordsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord.Builder getRecordsBuilder(
        int index) {
      return getRecordsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.SyncdRecordOrBuilder getRecordsOrBuilder(
        int index) {
      if (recordsBuilder_ == null) {
        return records_.get(index);  } else {
        return recordsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public java.util.List<? extends br.com.zapia.wpp.api.ws.binary.protos.SyncdRecordOrBuilder> 
         getRecordsOrBuilderList() {
      if (recordsBuilder_ != null) {
        return recordsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(records_);
      }
    }
    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord.Builder addRecordsBuilder() {
      return getRecordsFieldBuilder().addBuilder(
          br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord.getDefaultInstance());
    }
    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord.Builder addRecordsBuilder(
        int index) {
      return getRecordsFieldBuilder().addBuilder(
          index, br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord.getDefaultInstance());
    }
    /**
     * <code>repeated .binary.SyncdRecord records = 2;</code>
     */
    public java.util.List<br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord.Builder> 
         getRecordsBuilderList() {
      return getRecordsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord, br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord.Builder, br.com.zapia.wpp.api.ws.binary.protos.SyncdRecordOrBuilder> 
        getRecordsFieldBuilder() {
      if (recordsBuilder_ == null) {
        recordsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord, br.com.zapia.wpp.api.ws.binary.protos.SyncdRecord.Builder, br.com.zapia.wpp.api.ws.binary.protos.SyncdRecordOrBuilder>(
                records_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        records_ = null;
      }
      return recordsBuilder_;
    }

    private com.google.protobuf.ByteString mac_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes mac = 3;</code>
     * @return Whether the mac field is set.
     */
    @java.lang.Override
    public boolean hasMac() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes mac = 3;</code>
     * @return The mac.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMac() {
      return mac_;
    }
    /**
     * <code>optional bytes mac = 3;</code>
     * @param value The mac to set.
     * @return This builder for chaining.
     */
    public Builder setMac(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      mac_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes mac = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMac() {
      bitField0_ = (bitField0_ & ~0x00000004);
      mac_ = getDefaultInstance().getMac();
      onChanged();
      return this;
    }

    private br.com.zapia.wpp.api.ws.binary.protos.KeyId keyId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.KeyId, br.com.zapia.wpp.api.ws.binary.protos.KeyId.Builder, br.com.zapia.wpp.api.ws.binary.protos.KeyIdOrBuilder> keyIdBuilder_;
    /**
     * <code>optional .binary.KeyId keyId = 4;</code>
     * @return Whether the keyId field is set.
     */
    public boolean hasKeyId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .binary.KeyId keyId = 4;</code>
     * @return The keyId.
     */
    public br.com.zapia.wpp.api.ws.binary.protos.KeyId getKeyId() {
      if (keyIdBuilder_ == null) {
        return keyId_ == null ? br.com.zapia.wpp.api.ws.binary.protos.KeyId.getDefaultInstance() : keyId_;
      } else {
        return keyIdBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .binary.KeyId keyId = 4;</code>
     */
    public Builder setKeyId(br.com.zapia.wpp.api.ws.binary.protos.KeyId value) {
      if (keyIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        keyId_ = value;
        onChanged();
      } else {
        keyIdBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .binary.KeyId keyId = 4;</code>
     */
    public Builder setKeyId(
        br.com.zapia.wpp.api.ws.binary.protos.KeyId.Builder builderForValue) {
      if (keyIdBuilder_ == null) {
        keyId_ = builderForValue.build();
        onChanged();
      } else {
        keyIdBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .binary.KeyId keyId = 4;</code>
     */
    public Builder mergeKeyId(br.com.zapia.wpp.api.ws.binary.protos.KeyId value) {
      if (keyIdBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
            keyId_ != null &&
            keyId_ != br.com.zapia.wpp.api.ws.binary.protos.KeyId.getDefaultInstance()) {
          keyId_ =
            br.com.zapia.wpp.api.ws.binary.protos.KeyId.newBuilder(keyId_).mergeFrom(value).buildPartial();
        } else {
          keyId_ = value;
        }
        onChanged();
      } else {
        keyIdBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .binary.KeyId keyId = 4;</code>
     */
    public Builder clearKeyId() {
      if (keyIdBuilder_ == null) {
        keyId_ = null;
        onChanged();
      } else {
        keyIdBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }
    /**
     * <code>optional .binary.KeyId keyId = 4;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.KeyId.Builder getKeyIdBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getKeyIdFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .binary.KeyId keyId = 4;</code>
     */
    public br.com.zapia.wpp.api.ws.binary.protos.KeyIdOrBuilder getKeyIdOrBuilder() {
      if (keyIdBuilder_ != null) {
        return keyIdBuilder_.getMessageOrBuilder();
      } else {
        return keyId_ == null ?
            br.com.zapia.wpp.api.ws.binary.protos.KeyId.getDefaultInstance() : keyId_;
      }
    }
    /**
     * <code>optional .binary.KeyId keyId = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        br.com.zapia.wpp.api.ws.binary.protos.KeyId, br.com.zapia.wpp.api.ws.binary.protos.KeyId.Builder, br.com.zapia.wpp.api.ws.binary.protos.KeyIdOrBuilder> 
        getKeyIdFieldBuilder() {
      if (keyIdBuilder_ == null) {
        keyIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            br.com.zapia.wpp.api.ws.binary.protos.KeyId, br.com.zapia.wpp.api.ws.binary.protos.KeyId.Builder, br.com.zapia.wpp.api.ws.binary.protos.KeyIdOrBuilder>(
                getKeyId(),
                getParentForChildren(),
                isClean());
        keyId_ = null;
      }
      return keyIdBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:binary.SyncdSnapshot)
  }

  // @@protoc_insertion_point(class_scope:binary.SyncdSnapshot)
  private static final br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot();
  }

  public static br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<SyncdSnapshot>
      PARSER = new com.google.protobuf.AbstractParser<SyncdSnapshot>() {
    @java.lang.Override
    public SyncdSnapshot parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SyncdSnapshot(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SyncdSnapshot> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SyncdSnapshot> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.com.zapia.wpp.api.ws.binary.protos.SyncdSnapshot getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

