// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

public interface UnarchiveChatsSettingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.UnarchiveChatsSetting)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool unarchiveChats = 1;</code>
   * @return Whether the unarchiveChats field is set.
   */
  boolean hasUnarchiveChats();
  /**
   * <code>optional bool unarchiveChats = 1;</code>
   * @return The unarchiveChats.
   */
  boolean getUnarchiveChats();
}
