// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WAMessage.proto

package br.com.zapia.wpp.api.ws.binary.protos;

public interface WebFeaturesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binary.WebFeatures)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag labelsDisplay = 1;</code>
   * @return Whether the labelsDisplay field is set.
   */
  boolean hasLabelsDisplay();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag labelsDisplay = 1;</code>
   * @return The labelsDisplay.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getLabelsDisplay();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag voipIndividualOutgoing = 2;</code>
   * @return Whether the voipIndividualOutgoing field is set.
   */
  boolean hasVoipIndividualOutgoing();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag voipIndividualOutgoing = 2;</code>
   * @return The voipIndividualOutgoing.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getVoipIndividualOutgoing();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag groupsV3 = 3;</code>
   * @return Whether the groupsV3 field is set.
   */
  boolean hasGroupsV3();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag groupsV3 = 3;</code>
   * @return The groupsV3.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getGroupsV3();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag groupsV3Create = 4;</code>
   * @return Whether the groupsV3Create field is set.
   */
  boolean hasGroupsV3Create();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag groupsV3Create = 4;</code>
   * @return The groupsV3Create.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getGroupsV3Create();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag changeNumberV2 = 5;</code>
   * @return Whether the changeNumberV2 field is set.
   */
  boolean hasChangeNumberV2();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag changeNumberV2 = 5;</code>
   * @return The changeNumberV2.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getChangeNumberV2();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag queryStatusV3Thumbnail = 6;</code>
   * @return Whether the queryStatusV3Thumbnail field is set.
   */
  boolean hasQueryStatusV3Thumbnail();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag queryStatusV3Thumbnail = 6;</code>
   * @return The queryStatusV3Thumbnail.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getQueryStatusV3Thumbnail();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag liveLocations = 7;</code>
   * @return Whether the liveLocations field is set.
   */
  boolean hasLiveLocations();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag liveLocations = 7;</code>
   * @return The liveLocations.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getLiveLocations();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag queryVname = 8;</code>
   * @return Whether the queryVname field is set.
   */
  boolean hasQueryVname();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag queryVname = 8;</code>
   * @return The queryVname.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getQueryVname();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag voipIndividualIncoming = 9;</code>
   * @return Whether the voipIndividualIncoming field is set.
   */
  boolean hasVoipIndividualIncoming();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag voipIndividualIncoming = 9;</code>
   * @return The voipIndividualIncoming.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getVoipIndividualIncoming();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag quickRepliesQuery = 10;</code>
   * @return Whether the quickRepliesQuery field is set.
   */
  boolean hasQuickRepliesQuery();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag quickRepliesQuery = 10;</code>
   * @return The quickRepliesQuery.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getQuickRepliesQuery();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag payments = 11;</code>
   * @return Whether the payments field is set.
   */
  boolean hasPayments();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag payments = 11;</code>
   * @return The payments.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getPayments();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag stickerPackQuery = 12;</code>
   * @return Whether the stickerPackQuery field is set.
   */
  boolean hasStickerPackQuery();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag stickerPackQuery = 12;</code>
   * @return The stickerPackQuery.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getStickerPackQuery();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag liveLocationsFinal = 13;</code>
   * @return Whether the liveLocationsFinal field is set.
   */
  boolean hasLiveLocationsFinal();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag liveLocationsFinal = 13;</code>
   * @return The liveLocationsFinal.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getLiveLocationsFinal();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag labelsEdit = 14;</code>
   * @return Whether the labelsEdit field is set.
   */
  boolean hasLabelsEdit();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag labelsEdit = 14;</code>
   * @return The labelsEdit.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getLabelsEdit();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag mediaUpload = 15;</code>
   * @return Whether the mediaUpload field is set.
   */
  boolean hasMediaUpload();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag mediaUpload = 15;</code>
   * @return The mediaUpload.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getMediaUpload();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag mediaUploadRichQuickReplies = 18;</code>
   * @return Whether the mediaUploadRichQuickReplies field is set.
   */
  boolean hasMediaUploadRichQuickReplies();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag mediaUploadRichQuickReplies = 18;</code>
   * @return The mediaUploadRichQuickReplies.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getMediaUploadRichQuickReplies();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag vnameV2 = 19;</code>
   * @return Whether the vnameV2 field is set.
   */
  boolean hasVnameV2();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag vnameV2 = 19;</code>
   * @return The vnameV2.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getVnameV2();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag videoPlaybackUrl = 20;</code>
   * @return Whether the videoPlaybackUrl field is set.
   */
  boolean hasVideoPlaybackUrl();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag videoPlaybackUrl = 20;</code>
   * @return The videoPlaybackUrl.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getVideoPlaybackUrl();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag statusRanking = 21;</code>
   * @return Whether the statusRanking field is set.
   */
  boolean hasStatusRanking();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag statusRanking = 21;</code>
   * @return The statusRanking.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getStatusRanking();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag voipIndividualVideo = 22;</code>
   * @return Whether the voipIndividualVideo field is set.
   */
  boolean hasVoipIndividualVideo();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag voipIndividualVideo = 22;</code>
   * @return The voipIndividualVideo.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getVoipIndividualVideo();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag thirdPartyStickers = 23;</code>
   * @return Whether the thirdPartyStickers field is set.
   */
  boolean hasThirdPartyStickers();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag thirdPartyStickers = 23;</code>
   * @return The thirdPartyStickers.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getThirdPartyStickers();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag frequentlyForwardedSetting = 24;</code>
   * @return Whether the frequentlyForwardedSetting field is set.
   */
  boolean hasFrequentlyForwardedSetting();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag frequentlyForwardedSetting = 24;</code>
   * @return The frequentlyForwardedSetting.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getFrequentlyForwardedSetting();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag groupsV4JoinPermission = 25;</code>
   * @return Whether the groupsV4JoinPermission field is set.
   */
  boolean hasGroupsV4JoinPermission();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag groupsV4JoinPermission = 25;</code>
   * @return The groupsV4JoinPermission.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getGroupsV4JoinPermission();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag recentStickers = 26;</code>
   * @return Whether the recentStickers field is set.
   */
  boolean hasRecentStickers();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag recentStickers = 26;</code>
   * @return The recentStickers.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getRecentStickers();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag catalog = 27;</code>
   * @return Whether the catalog field is set.
   */
  boolean hasCatalog();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag catalog = 27;</code>
   * @return The catalog.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getCatalog();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag starredStickers = 28;</code>
   * @return Whether the starredStickers field is set.
   */
  boolean hasStarredStickers();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag starredStickers = 28;</code>
   * @return The starredStickers.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getStarredStickers();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag voipGroupCall = 29;</code>
   * @return Whether the voipGroupCall field is set.
   */
  boolean hasVoipGroupCall();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag voipGroupCall = 29;</code>
   * @return The voipGroupCall.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getVoipGroupCall();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag templateMessage = 30;</code>
   * @return Whether the templateMessage field is set.
   */
  boolean hasTemplateMessage();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag templateMessage = 30;</code>
   * @return The templateMessage.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getTemplateMessage();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag templateMessageInteractivity = 31;</code>
   * @return Whether the templateMessageInteractivity field is set.
   */
  boolean hasTemplateMessageInteractivity();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag templateMessageInteractivity = 31;</code>
   * @return The templateMessageInteractivity.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getTemplateMessageInteractivity();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag ephemeralMessages = 32;</code>
   * @return Whether the ephemeralMessages field is set.
   */
  boolean hasEphemeralMessages();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag ephemeralMessages = 32;</code>
   * @return The ephemeralMessages.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getEphemeralMessages();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag e2ENotificationSync = 33;</code>
   * @return Whether the e2ENotificationSync field is set.
   */
  boolean hasE2ENotificationSync();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag e2ENotificationSync = 33;</code>
   * @return The e2ENotificationSync.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getE2ENotificationSync();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag recentStickersV2 = 34;</code>
   * @return Whether the recentStickersV2 field is set.
   */
  boolean hasRecentStickersV2();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag recentStickersV2 = 34;</code>
   * @return The recentStickersV2.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getRecentStickersV2();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag recentStickersV3 = 36;</code>
   * @return Whether the recentStickersV3 field is set.
   */
  boolean hasRecentStickersV3();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag recentStickersV3 = 36;</code>
   * @return The recentStickersV3.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getRecentStickersV3();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag userNotice = 37;</code>
   * @return Whether the userNotice field is set.
   */
  boolean hasUserNotice();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag userNotice = 37;</code>
   * @return The userNotice.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getUserNotice();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag support = 39;</code>
   * @return Whether the support field is set.
   */
  boolean hasSupport();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag support = 39;</code>
   * @return The support.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getSupport();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag groupUiiCleanup = 40;</code>
   * @return Whether the groupUiiCleanup field is set.
   */
  boolean hasGroupUiiCleanup();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag groupUiiCleanup = 40;</code>
   * @return The groupUiiCleanup.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getGroupUiiCleanup();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag groupDogfoodingInternalOnly = 41;</code>
   * @return Whether the groupDogfoodingInternalOnly field is set.
   */
  boolean hasGroupDogfoodingInternalOnly();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag groupDogfoodingInternalOnly = 41;</code>
   * @return The groupDogfoodingInternalOnly.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getGroupDogfoodingInternalOnly();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag settingsSync = 42;</code>
   * @return Whether the settingsSync field is set.
   */
  boolean hasSettingsSync();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag settingsSync = 42;</code>
   * @return The settingsSync.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getSettingsSync();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag archiveV2 = 43;</code>
   * @return Whether the archiveV2 field is set.
   */
  boolean hasArchiveV2();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag archiveV2 = 43;</code>
   * @return The archiveV2.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getArchiveV2();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag ephemeralAllowGroupMembers = 44;</code>
   * @return Whether the ephemeralAllowGroupMembers field is set.
   */
  boolean hasEphemeralAllowGroupMembers();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag ephemeralAllowGroupMembers = 44;</code>
   * @return The ephemeralAllowGroupMembers.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getEphemeralAllowGroupMembers();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag ephemeral24HDuration = 45;</code>
   * @return Whether the ephemeral24HDuration field is set.
   */
  boolean hasEphemeral24HDuration();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag ephemeral24HDuration = 45;</code>
   * @return The ephemeral24HDuration.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getEphemeral24HDuration();

  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag mdForceUpgrade = 46;</code>
   * @return Whether the mdForceUpgrade field is set.
   */
  boolean hasMdForceUpgrade();
  /**
   * <code>optional .binary.WebFeatures.WebFeaturesFlag mdForceUpgrade = 46;</code>
   * @return The mdForceUpgrade.
   */
  br.com.zapia.wpp.api.ws.binary.protos.WebFeatures.WebFeaturesFlag getMdForceUpgrade();
}
